import { Prisma } from "@/generated/prisma/client";
import { prisma } from "@/lib/db/prisma";
import { uniqueSlug } from "@/lib/cms/slug";
import { aiToolCategorySchema, aiToolListQuerySchema, aiToolSchema } from "@/lib/validation/ai-tools";
import { auditService } from "@/services/audit/audit.service";
import type { CurrentSession } from "@/lib/auth/session";

function textDoc(text:string):Prisma.InputJsonValue{return {type:"doc",content:text.split(/\n\n+/).filter(Boolean).map(paragraph=>({type:"paragraph",content:[{type:"text",text:paragraph.trim()}]}))};}
function jsonList(v:unknown):string[]{return Array.isArray(v)?v.filter((x):x is string=>typeof x==="string"):[]}
function snapshotTool(x:any){return {name:x.name,websiteUrl:x.websiteUrl,pricingModel:x.pricingModel,startingPrice:x.startingPrice?.toString?.()??x.startingPrice,currency:x.currency,rating:x.rating?.toString?.()??x.rating,freeTrial:x.freeTrial,apiAvailable:x.apiAvailable,verified:x.verified,lastReviewedAt:x.lastReviewedAt?.toISOString?.()??x.lastReviewedAt};}
function changed(before:any,after:any){const out:Record<string,{before:unknown;after:unknown}>={};for(const k of Object.keys(after)){if(JSON.stringify(before?.[k]??null)!==JSON.stringify(after[k]??null))out[k]={before:before?.[k]??null,after:after[k]??null};}return out;}

async function slugExists(slug:string,exceptId?:string){return !!(await prisma.aiTool.findFirst({where:{slug,...(exceptId?{id:{not:exceptId}}:{})},select:{id:true}}))}
async function categorySlugExists(slug:string,exceptId?:string){return !!(await prisma.aiToolCategory.findFirst({where:{slug,...(exceptId?{id:{not:exceptId}}:{})},select:{id:true}}))}
async function nonReciprocalAlternatives(tx:any,sourceToolId:string,ids:string[]){const unique=[...new Set(ids)].filter(x=>x!==sourceToolId);if(!unique.length)return [];const reverse=await tx.aiToolAlternative.findMany({where:{sourceToolId:{in:unique},targetToolId:sourceToolId},select:{sourceToolId:true}});const blocked=new Set(reverse.map((x:any)=>x.sourceToolId));return unique.filter(x=>!blocked.has(x));}

export const aiToolService={
  async adminList({q="",status="",categoryId="",page=1,limit=20}:{q?:string;status?:string;categoryId?:string;page?:number;limit?:number}){
    const where:Prisma.AiToolWhereInput={deletedAt:null,...(q?{OR:[{name:{contains:q}},{shortDescription:{contains:q}}]}:{}),...(status?{status:status as any}:{}),...(categoryId?{categoryId}:{})};
    const [items,total]=await prisma.$transaction([prisma.aiTool.findMany({where,include:{category:true,logo:true,_count:{select:{features:true,useCases:true,reviews:true}}},orderBy:{updatedAt:"desc"},skip:(page-1)*limit,take:limit}),prisma.aiTool.count({where})]);
    return {items,total,page,limit,pages:Math.max(1,Math.ceil(total/limit))};
  },
  adminGet:(id:string)=>prisma.aiTool.findFirst({where:{id,deletedAt:null},include:{category:true,logo:{include:{variants:true}},features:{orderBy:{sortOrder:"asc"}},useCases:{orderBy:{sortOrder:"asc"}},screenshots:{include:{media:{include:{variants:true}}},orderBy:{sortOrder:"asc"}},alternativesFrom:{include:{targetTool:{select:{id:true,name:true,slug:true}}},orderBy:{sortOrder:"asc"}}}}),
  async create(raw:unknown,session:CurrentSession){
    const v=aiToolSchema.parse(raw); const slug=await uniqueSlug(v.slug||v.name,s=>slugExists(s));
    const row=await prisma.$transaction(async tx=>{const tool=await tx.aiTool.create({data:{name:v.name,slug,logoId:v.logoId||null,websiteUrl:v.websiteUrl,affiliateUrl:v.affiliateUrl||null,shortDescription:v.shortDescription,fullDescription:textDoc(v.fullDescriptionText),categoryId:v.categoryId,pricingModel:v.pricingModel,startingPrice:v.startingPrice??null,currency:v.currency||null,rating:v.rating??null,reviewCount:v.reviewCount,pros:v.pros,cons:v.cons,platforms:v.platforms,integrations:v.integrations,apiAvailable:v.apiAvailable,freeTrial:v.freeTrial,featured:v.featured,verified:v.verified,status:v.status,lastReviewedAt:v.lastReviewedAt?new Date(v.lastReviewedAt):null,pricingVerifiedAt:v.pricingVerifiedAt?new Date(v.pricingVerifiedAt):null,officialUrlVerifiedAt:v.officialUrlVerifiedAt?new Date(v.officialUrlVerifiedAt):null,featuresVerifiedAt:v.featuresVerifiedAt?new Date(v.featuresVerifiedAt):null}}); if(v.useCases.length) await tx.aiToolUseCase.createMany({data:v.useCases.map((name,sortOrder)=>({aiToolId:tool.id,name,sortOrder}))}); if(v.features.length) await tx.aiToolFeature.createMany({data:v.features.map((f,sortOrder)=>({aiToolId:tool.id,name:f.name,description:f.description||null,sortOrder}))}); if(v.screenshotIds.length) await tx.aiToolScreenshot.createMany({data:v.screenshotIds.map((mediaId,sortOrder)=>({aiToolId:tool.id,mediaId,sortOrder}))}); if(v.alternativeIds.length){const ids=await nonReciprocalAlternatives(tx,tool.id,v.alternativeIds);if(ids.length)await tx.aiToolAlternative.createMany({data:ids.map((targetToolId,sortOrder)=>({sourceToolId:tool.id,targetToolId,sortOrder})),skipDuplicates:true});} await tx.aiToolChange.create({data:{aiToolId:tool.id,changedById:session.user.id,changeType:"CREATED",summary:"AI tool created",changes:{after:snapshotTool(tool)} as any}}); return tool;});
    await auditService.record({userId:session.user.id,action:"ai-tool.create",entityType:"AiTool",entityId:row.id}); return row;
  },
  async update(id:string,raw:unknown,session:CurrentSession){
    const v=aiToolSchema.parse(raw); const current=await prisma.aiTool.findFirst({where:{id,deletedAt:null},include:{features:{orderBy:{sortOrder:"asc"}}}}); if(!current)return null; const slug=await uniqueSlug(v.slug||v.name,s=>slugExists(s,id),current.slug);
    const row=await prisma.$transaction(async tx=>{await tx.aiToolUseCase.deleteMany({where:{aiToolId:id}}); await tx.aiToolFeature.deleteMany({where:{aiToolId:id}}); await tx.aiToolScreenshot.deleteMany({where:{aiToolId:id}}); await tx.aiToolAlternative.deleteMany({where:{sourceToolId:id}}); const tool=await tx.aiTool.update({where:{id},data:{name:v.name,slug,logoId:v.logoId||null,websiteUrl:v.websiteUrl,affiliateUrl:v.affiliateUrl||null,shortDescription:v.shortDescription,fullDescription:textDoc(v.fullDescriptionText),categoryId:v.categoryId,pricingModel:v.pricingModel,startingPrice:v.startingPrice??null,currency:v.currency||null,rating:v.rating??null,reviewCount:v.reviewCount,pros:v.pros,cons:v.cons,platforms:v.platforms,integrations:v.integrations,apiAvailable:v.apiAvailable,freeTrial:v.freeTrial,featured:v.featured,verified:v.verified,status:v.status,lastReviewedAt:v.lastReviewedAt?new Date(v.lastReviewedAt):null,pricingVerifiedAt:v.pricingVerifiedAt?new Date(v.pricingVerifiedAt):null,officialUrlVerifiedAt:v.officialUrlVerifiedAt?new Date(v.officialUrlVerifiedAt):null,featuresVerifiedAt:v.featuresVerifiedAt?new Date(v.featuresVerifiedAt):null}}); if(v.useCases.length) await tx.aiToolUseCase.createMany({data:v.useCases.map((name,sortOrder)=>({aiToolId:id,name,sortOrder}))}); if(v.features.length) await tx.aiToolFeature.createMany({data:v.features.map((f,sortOrder)=>({aiToolId:id,name:f.name,description:f.description||null,sortOrder}))}); if(v.screenshotIds.length) await tx.aiToolScreenshot.createMany({data:v.screenshotIds.map((mediaId,sortOrder)=>({aiToolId:id,mediaId,sortOrder}))}); if(v.alternativeIds.length){const ids=await nonReciprocalAlternatives(tx,id,v.alternativeIds);if(ids.length)await tx.aiToolAlternative.createMany({data:ids.map((targetToolId,sortOrder)=>({sourceToolId:id,targetToolId,sortOrder})),skipDuplicates:true});} const changes=changed(snapshotTool(current),snapshotTool(tool)); const beforeFeatures=current.features.map(f=>({name:f.name,description:f.description||""})); if(JSON.stringify(beforeFeatures)!==JSON.stringify(v.features)) changes.features={before:beforeFeatures,after:v.features}; if(Object.keys(changes).length) await tx.aiToolChange.create({data:{aiToolId:id,changedById:session.user.id,changeType:"UPDATED",summary:`Updated ${Object.keys(changes).join(", ")}`,changes:changes as any}}); return tool;});
    await auditService.record({userId:session.user.id,action:"ai-tool.update",entityType:"AiTool",entityId:id}); return row;
  },
  async remove(id:string,session:CurrentSession){const row=await prisma.aiTool.update({where:{id},data:{deletedAt:new Date(),status:"ARCHIVED"}});await auditService.record({userId:session.user.id,action:"ai-tool.delete",entityType:"AiTool",entityId:id});return row;},
  categories:()=>prisma.aiToolCategory.findMany({include:{_count:{select:{tools:true}}},orderBy:[{sortOrder:"asc"},{name:"asc"}]}),
  async createCategory(raw:unknown){const v=aiToolCategorySchema.parse(raw);const slug=await uniqueSlug(v.slug||v.name,s=>categorySlugExists(s));return prisma.aiToolCategory.create({data:{name:v.name,slug,description:v.description||null,sortOrder:v.sortOrder}})},
  async updateCategory(id:string,raw:unknown){const v=aiToolCategorySchema.parse(raw);const cur=await prisma.aiToolCategory.findUnique({where:{id}});if(!cur)return null;const slug=await uniqueSlug(v.slug||v.name,s=>categorySlugExists(s,id),cur.slug);return prisma.aiToolCategory.update({where:{id},data:{name:v.name,slug,description:v.description||null,sortOrder:v.sortOrder}})},
  async deleteCategory(id:string){const used=await prisma.aiTool.count({where:{categoryId:id,deletedAt:null}});if(used)throw new Error("Move or archive tools in this category before deleting it.");return prisma.aiToolCategory.delete({where:{id}})},
  async publicList(raw:Record<string,string|undefined>){
    const q=aiToolListQuerySchema.parse(raw); const where:Prisma.AiToolWhereInput={status:"PUBLISHED",deletedAt:null,...(q.q?{OR:[{name:{contains:q.q}},{shortDescription:{contains:q.q}},{useCases:{some:{name:{contains:q.q}}}},{features:{some:{name:{contains:q.q}}}}]}:{}),...(q.category?{category:{slug:q.category}}:{}),...(q.pricing?{pricingModel:q.pricing}:{}),...(q.minRating!=null?{rating:{gte:q.minRating}}:{}),...(q.platform?{platforms:{array_contains:q.platform}}:{}),...(q.useCase?{useCases:{some:{name:{contains:q.useCase}}}}:{}),...(q.freeTrial==="yes"?{freeTrial:true}:{})};
    let orderBy:Prisma.AiToolOrderByWithRelationInput[]; switch(q.sort){case"most-popular":orderBy=[{views:"desc"},{reviewCount:"desc"}];break;case"newest":orderBy=[{createdAt:"desc"}];break;case"recently-updated":orderBy=[{updatedAt:"desc"}];break;case"price-low":orderBy=[{startingPrice:"asc"},{rating:"desc"}];break;case"price-high":orderBy=[{startingPrice:"desc"},{rating:"desc"}];break;default:orderBy=[{rating:"desc"},{reviewCount:"desc"}];}
    const [items,total,categories]=await prisma.$transaction([prisma.aiTool.findMany({where,include:{category:true,logo:{include:{variants:true}},features:{take:4,orderBy:{sortOrder:"asc"}},useCases:{take:4,orderBy:{sortOrder:"asc"}}},orderBy,skip:(q.page-1)*q.limit,take:q.limit}),prisma.aiTool.count({where}),prisma.aiToolCategory.findMany({where:{tools:{some:{status:"PUBLISHED",deletedAt:null}}},orderBy:[{sortOrder:"asc"},{name:"asc"}]})]);
    return {items,total,categories,page:q.page,limit:q.limit,pages:Math.max(1,Math.ceil(total/q.limit)),query:q};
  },
  publicGet:(slug:string)=>prisma.aiTool.findFirst({where:{slug,status:"PUBLISHED",deletedAt:null},include:{category:true,logo:{include:{variants:true}},features:{orderBy:{sortOrder:"asc"}},useCases:{orderBy:{sortOrder:"asc"}},screenshots:{include:{media:{include:{variants:true}}},orderBy:{sortOrder:"asc"}},reviews:{where:{status:"PUBLISHED"},take:4,orderBy:{publishedAt:"desc"}},alternativesFrom:{include:{targetTool:{include:{category:true,logo:{include:{variants:true}}}}},orderBy:{sortOrder:"asc"}}}}),
  related:(id:string,categoryId:string)=>prisma.aiTool.findMany({where:{id:{not:id},categoryId,status:"PUBLISHED",deletedAt:null},include:{category:true,logo:{include:{variants:true}},features:{take:3},useCases:{take:3}},orderBy:[{featured:"desc"},{rating:"desc"}],take:3}),
  featured:()=>prisma.aiTool.findMany({where:{status:"PUBLISHED",deletedAt:null,featured:true},include:{category:true,logo:{include:{variants:true}},features:{take:3},useCases:{take:3}},orderBy:[{rating:"desc"},{updatedAt:"desc"}],take:4}),
  async incrementView(id:string){await prisma.aiTool.update({where:{id},data:{views:{increment:1}}})},
  history:(id:string)=>prisma.aiToolChange.findMany({where:{aiToolId:id},include:{changedBy:{select:{name:true,email:true}}},orderBy:{createdAt:"desc"},take:100}),
  stale:(days=120)=>prisma.aiTool.findMany({where:{deletedAt:null,status:{not:"ARCHIVED"},OR:[{lastReviewedAt:null},{lastReviewedAt:{lt:new Date(Date.now()-days*86400000)}}]},include:{category:true},orderBy:[{lastReviewedAt:"asc"},{updatedAt:"asc"}]}),
  alternativeCandidates:(excludeId?:string)=>prisma.aiTool.findMany({where:{deletedAt:null,status:{not:"ARCHIVED"},...(excludeId?{id:{not:excludeId}}:{})},select:{id:true,name:true,slug:true},orderBy:{name:"asc"},take:250}),
  jsonList,
};
