import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes } from "node:crypto";
import { prisma } from "@/lib/db/prisma";
import { env } from "@/lib/env";
import { randomToken, sha256 } from "@/lib/security/crypto";

const ALPHABET="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
function base32Encode(buf:Buffer){let bits="",out="";for(const b of buf)bits+=b.toString(2).padStart(8,"0");for(let i=0;i<bits.length;i+=5)out+=ALPHABET[parseInt(bits.slice(i,i+5).padEnd(5,"0"),2)];return out;}
function base32Decode(s:string){let bits="";for(const c of s.replace(/=|\s/g,"").toUpperCase()){const i=ALPHABET.indexOf(c);if(i<0)throw new Error("Invalid base32");bits+=i.toString(2).padStart(5,"0");}const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(bytes);}
const key=()=>createHash("sha256").update(env.SESSION_SECRET+":2fa").digest();
function encrypt(v:string){const iv=randomBytes(12),c=createCipheriv("aes-256-gcm",key(),iv);const enc=Buffer.concat([c.update(v,"utf8"),c.final()]);return [iv,c.getAuthTag(),enc].map(x=>x.toString("base64url")).join(".");}
function decrypt(v:string){const [a,b,c]=v.split(".");const d=createDecipheriv("aes-256-gcm",key(),Buffer.from(a,"base64url"));d.setAuthTag(Buffer.from(b,"base64url"));return Buffer.concat([d.update(Buffer.from(c,"base64url")),d.final()]).toString("utf8");}
export function totpCode(secret:string,time=Date.now()){const counter=Math.floor(time/30000);const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(counter));const h=createHmac("sha1",base32Decode(secret)).update(b).digest();const o=h[h.length-1]&15;return (((h[o]&127)<<24)|(h[o+1]<<16)|(h[o+2]<<8)|h[o+3])%1000000;}
export function verifyTotp(secret:string,code:string){return [-1,0,1].some(w=>String(totpCode(secret,Date.now()+w*30000)).padStart(6,"0")===code.replace(/\s/g,""));}
export async function beginTwoFactorSetup(userId:string,email:string){const secret=base32Encode(randomBytes(20));await prisma.twoFactorCredential.upsert({where:{userId},update:{secretEncrypted:encrypt(secret),enabled:false,verifiedAt:null},create:{userId,secretEncrypted:encrypt(secret)}});const issuer="PushStream";return {secret,otpauthUrl:`otpauth://totp/${encodeURIComponent(issuer)}:${encodeURIComponent(email)}?secret=${secret}&issuer=${encodeURIComponent(issuer)}&digits=6&period=30`};}
export async function enableTwoFactor(userId:string,code:string){const cred=await prisma.twoFactorCredential.findUnique({where:{userId}});if(!cred||!verifyTotp(decrypt(cred.secretEncrypted),code))throw new Error("INVALID_TOTP");const codes=Array.from({length:10},()=>randomToken(6).slice(0,10).toUpperCase());await prisma.$transaction([prisma.twoFactorCredential.update({where:{id:cred.id},data:{enabled:true,verifiedAt:new Date()}}),prisma.twoFactorBackupCode.deleteMany({where:{credentialId:cred.id}}),prisma.twoFactorBackupCode.createMany({data:codes.map(c=>({credentialId:cred.id,codeHash:sha256(c)}))})]);return codes;}
export async function disableTwoFactor(userId:string,code:string){const cred=await prisma.twoFactorCredential.findUnique({where:{userId}});if(!cred) return; if(!verifyTotp(decrypt(cred.secretEncrypted),code))throw new Error("INVALID_TOTP");await prisma.twoFactorCredential.delete({where:{id:cred.id}});}
export async function verifyUserSecondFactor(userId:string,code:string){const cred=await prisma.twoFactorCredential.findUnique({where:{userId},include:{backupCodes:true}});if(!cred?.enabled)return false;if(verifyTotp(decrypt(cred.secretEncrypted),code))return true;const hash=sha256(code.trim().toUpperCase());const backup=cred.backupCodes.find(x=>!x.usedAt&&x.codeHash===hash);if(!backup)return false;await prisma.twoFactorBackupCode.update({where:{id:backup.id},data:{usedAt:new Date()}});return true;}
