"use server";
import { revalidatePath } from "next/cache";
import { CACHE_TAGS,revalidatePublicContent } from "@/lib/cache/invalidation";
import { requirePermission } from "@/lib/auth/session";
import { auditService } from "@/services/audit/audit.service";
import { upsertSettings } from "@/services/system/settings.service";
const text=(f:FormData,k:string,max=500)=>String(f.get(k)??"").trim().slice(0,max);
export async function saveGeneralSettings(formData:FormData){const s=await requirePermission("settings.edit");const values={"general.siteName":text(formData,"siteName",120),"general.tagline":text(formData,"tagline",200),"general.adminEmail":text(formData,"adminEmail",255),"general.timezone":text(formData,"timezone",80),"general.logoUrl":text(formData,"logoUrl",1000),"general.faviconUrl":text(formData,"faviconUrl",1000),"general.defaultAuthorId":text(formData,"defaultAuthorId",100),"general.footerBrandCardTitle":text(formData,"footerBrandCardTitle",180),"general.footerBrandCardBody":text(formData,"footerBrandCardBody",500),"general.footerCommunityMessage":text(formData,"footerCommunityMessage",180)};await upsertSettings("general",values,s.user.id);await auditService.record({userId:s.user.id,action:"settings.general.update",entityType:"SiteSetting",metadata:{keys:Object.keys(values)}});revalidatePublicContent([CACHE_TAGS.settings,CACHE_TAGS.chrome],["/"]);revalidatePath("/","layout");}
export async function saveSocialSettings(formData:FormData){const s=await requirePermission("settings.edit");const values={"social.facebook":text(formData,"facebook",1000),"social.twitter":text(formData,"twitter",1000),"social.linkedin":text(formData,"linkedin",1000),"social.youtube":text(formData,"youtube",1000),"social.instagram":text(formData,"instagram",1000)};await upsertSettings("social",values,s.user.id);await auditService.record({userId:s.user.id,action:"settings.social.update",entityType:"SiteSetting"});revalidatePublicContent([CACHE_TAGS.settings,CACHE_TAGS.chrome],["/"]);revalidatePath("/","layout");}
export async function saveIntegrationSettings(formData:FormData){const s=await requirePermission("settings.edit");const values={"analytics.googleAnalyticsId":text(formData,"ga",100),"analytics.googleTagManagerId":text(formData,"gtm",100),"comments.enabled":formData.get("commentsEnabled")==="on","comments.requireModeration":formData.get("moderation")==="on","newsletter.confirmationRequired":formData.get("confirmation")==="on","performance.readingWordsPerMinute":Math.min(600,Math.max(100,Number(formData.get("wpm")||225)))};await upsertSettings("integrations",values,s.user.id);await auditService.record({userId:s.user.id,action:"settings.integrations.update",entityType:"SiteSetting"});revalidatePublicContent([CACHE_TAGS.settings,CACHE_TAGS.chrome],["/"]);revalidatePath("/","layout");}
