import { prisma } from "@/lib/db/prisma";
import { sha256 } from "@/lib/security/crypto";
type Node={type?:string;text?:string;content?:Node[];marks?:Array<{type?:string;attrs?:Record<string,unknown>}>};
export type ExtractedLink={url:string;text:string};
function extract(doc:unknown){const out:ExtractedLink[]=[];function walk(n:Node|undefined){if(!n)return;if(n.text){for(const m of n.marks||[])if(m.type==="link"){const url=String(m.attrs?.href||"").trim();if(url)out.push({url,text:n.text})}}n.content?.forEach(walk)}walk(doc as Node);return out}
function internalPath(url:string){try{if(url.startsWith("/"))return url.split(/[?#]/)[0];const u=new URL(url);if(u.hostname==="pushstream.online"||u.hostname==="www.pushstream.online")return u.pathname;return null}catch{return null}}
async function exists(path:string){if(path==="/"||["/ai-tools","/wordpress","/development","/how-to","/reviews","/online-business","/search","/contact"].includes(path))return true;let m=path.match(/^\/article\/([^/]+)$/);if(m)return Boolean(await prisma.post.findFirst({where:{slug:decodeURIComponent(m[1]),status:"PUBLISHED",deletedAt:null},select:{id:true}}));m=path.match(/^\/category\/([^/]+)$/);if(m)return Boolean(await prisma.category.findUnique({where:{slug:decodeURIComponent(m[1])},select:{id:true}}));m=path.match(/^\/tag\/([^/]+)$/);if(m)return Boolean(await prisma.tag.findUnique({where:{slug:decodeURIComponent(m[1])},select:{id:true}}));m=path.match(/^\/author\/([^/]+)$/);if(m)return Boolean(await prisma.authorProfile.findUnique({where:{slug:decodeURIComponent(m[1])},select:{id:true}}));m=path.match(/^\/ai-tools\/([^/]+)$/);if(m)return Boolean(await prisma.aiTool.findFirst({where:{slug:decodeURIComponent(m[1]),status:"PUBLISHED",deletedAt:null},select:{id:true}}));m=path.match(/^\/reviews\/([^/]+)$/);if(m)return Boolean(await prisma.review.findFirst({where:{slug:decodeURIComponent(m[1]),status:"PUBLISHED",deletedAt:null},select:{id:true}}));return true}
export const linkIntelligenceService={
 extract,
 async suggestions(postId:string,query=""){const current=await prisma.post.findUnique({where:{id:postId},select:{categoryId:true,tags:{select:{tagId:true}}}});if(!current)return[];const tagIds=current.tags.map(x=>x.tagId);return prisma.post.findMany({where:{id:{not:postId},status:"PUBLISHED",deletedAt:null,OR:[...(current.categoryId?[{categoryId:current.categoryId}]:[]),...(tagIds.length?[{tags:{some:{tagId:{in:tagIds}}}}]:[]),...(query.trim()?[{title:{contains:query.trim()}}]:[])]},select:{id:true,title:true,slug:true,publishedAt:true,category:{select:{name:true}}},orderBy:{publishedAt:"desc"},take:10})},
 async orphanReport(q=""){const posts=await prisma.post.findMany({where:{status:"PUBLISHED",deletedAt:null,...(q?{title:{contains:q}}:{})},select:{id:true,title:true,slug:true,publishedAt:true,content:true,category:{select:{name:true}}},orderBy:{publishedAt:"desc"},take:500});const inbound=new Map(posts.map(x=>[x.id,0]));const byPath=new Map(posts.map(x=>[`/article/${x.slug}`,x.id]));const rows=posts.map(post=>{const links=extract(post.content).map(x=>internalPath(x.url)).filter(Boolean) as string[];const unique=[...new Set(links)];for(const path of unique){const id=byPath.get(path);if(id&&id!==post.id)inbound.set(id,(inbound.get(id)||0)+1)}return{post,outbound:unique.length}});return rows.map(x=>({...x,inbound:inbound.get(x.post.id)||0})).sort((a,b)=>a.inbound-b.inbound||a.outbound-b.outbound)},
 async scanPost(postId:string){const post=await prisma.post.findUnique({where:{id:postId},select:{id:true,content:true}});if(!post)throw new Error("Post not found");const links=extract(post.content);const current=new Set<string>();for(const link of links){const path=internalPath(link.url);if(!path)continue;const ok=await exists(path);if(!ok){current.add(link.url);await prisma.brokenLink.upsert({where:{sourcePostId_urlHash:{sourcePostId:postId,urlHash:sha256(link.url)}},update:{url:link.url,linkText:link.text,httpStatus:404,lastCheckedAt:new Date(),ignoredAt:null},create:{sourcePostId:postId,url:link.url,urlHash:sha256(link.url),linkText:link.text,httpStatus:404,lastCheckedAt:new Date()}})}}await prisma.brokenLink.deleteMany({where:{sourcePostId:postId,ignoredAt:null,url:{notIn:[...current]}}});return{checked:links.length,broken:current.size}},
 async scanPublished(limit=200){const posts=await prisma.post.findMany({where:{status:"PUBLISHED",deletedAt:null},select:{id:true},orderBy:{updatedAt:"desc"},take:Math.min(Math.max(limit,1),500)});let checked=0,broken=0;for(const p of posts){const r=await this.scanPost(p.id);checked+=r.checked;broken+=r.broken}return{posts:posts.length,checked,broken}},
 async brokenList(q=""){return prisma.brokenLink.findMany({where:{ignoredAt:null,...(q?{OR:[{url:{contains:q}},{sourcePost:{title:{contains:q}}}]}:{})},include:{sourcePost:{select:{id:true,title:true,slug:true}}},orderBy:[{lastCheckedAt:"desc"},{createdAt:"desc"}],take:500})},
 async ignore(id:string){return prisma.brokenLink.update({where:{id},data:{ignoredAt:new Date()}})}
};
