-- Phase 23 discovery/search structures
ALTER TABLE `SearchLog` ADD COLUMN `clickedResult` VARCHAR(600) NULL, ADD COLUMN `clickedType` VARCHAR(40) NULL, ADD COLUMN `clickedAt` DATETIME(3) NULL;
CREATE INDEX `SearchLog_clickedAt_createdAt_idx` ON `SearchLog`(`clickedAt`,`createdAt`);

CREATE TABLE `ContentSeries` (`id` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `slug` VARCHAR(191) NOT NULL, `description` TEXT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `ContentSeries_slug_key`(`slug`), INDEX `ContentSeries_updatedAt_idx`(`updatedAt`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `ContentSeriesPost` (`seriesId` VARCHAR(191) NOT NULL, `postId` VARCHAR(191) NOT NULL, `sortOrder` INTEGER NOT NULL DEFAULT 0, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`seriesId`,`postId`), UNIQUE INDEX `ContentSeriesPost_postId_key`(`postId`), INDEX `ContentSeriesPost_seriesId_sortOrder_idx`(`seriesId`,`sortOrder`), CONSTRAINT `ContentSeriesPost_seriesId_fkey` FOREIGN KEY (`seriesId`) REFERENCES `ContentSeries`(`id`) ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT `ContentSeriesPost_postId_fkey` FOREIGN KEY (`postId`) REFERENCES `Post`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `FeaturedCollection` (`id` VARCHAR(191) NOT NULL, `title` VARCHAR(191) NOT NULL, `slug` VARCHAR(191) NOT NULL, `description` TEXT NULL, `coverImageId` VARCHAR(191) NULL, `seoTitle` VARCHAR(191) NULL, `seoDescription` TEXT NULL, `robotsIndex` BOOLEAN NOT NULL DEFAULT true, `published` BOOLEAN NOT NULL DEFAULT false, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `FeaturedCollection_slug_key`(`slug`), INDEX `FeaturedCollection_published_updatedAt_idx`(`published`,`updatedAt`), INDEX `FeaturedCollection_coverImageId_idx`(`coverImageId`), CONSTRAINT `FeaturedCollection_coverImageId_fkey` FOREIGN KEY (`coverImageId`) REFERENCES `Media`(`id`) ON DELETE SET NULL ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `FeaturedCollectionItem` (`id` VARCHAR(191) NOT NULL, `collectionId` VARCHAR(191) NOT NULL, `itemType` ENUM('POST','AI_TOOL','REVIEW','RESOURCE') NOT NULL, `itemId` VARCHAR(191) NOT NULL, `sortOrder` INTEGER NOT NULL DEFAULT 0, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE INDEX `FeaturedCollectionItem_collectionId_itemType_itemId_key`(`collectionId`,`itemType`,`itemId`), INDEX `FeaturedCollectionItem_collectionId_sortOrder_idx`(`collectionId`,`sortOrder`), INDEX `FeaturedCollectionItem_itemType_itemId_idx`(`itemType`,`itemId`), CONSTRAINT `FeaturedCollectionItem_collectionId_fkey` FOREIGN KEY (`collectionId`) REFERENCES `FeaturedCollection`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `ResourceCategory` (`id` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `slug` VARCHAR(191) NOT NULL, `description` TEXT NULL, `sortOrder` INTEGER NOT NULL DEFAULT 0, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `ResourceCategory_slug_key`(`slug`), INDEX `ResourceCategory_sortOrder_name_idx`(`sortOrder`,`name`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `Resource` (`id` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `slug` VARCHAR(191) NOT NULL, `description` TEXT NOT NULL, `url` TEXT NOT NULL, `affiliateUrl` TEXT NULL, `categoryId` VARCHAR(191) NOT NULL, `pricing` ENUM('FREE','FREEMIUM','PAID','CONTACT') NOT NULL DEFAULT 'FREE', `logoId` VARCHAR(191) NULL, `featured` BOOLEAN NOT NULL DEFAULT false, `status` ENUM('DRAFT','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT', `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `Resource_slug_key`(`slug`), INDEX `Resource_status_featured_updatedAt_idx`(`status`,`featured`,`updatedAt`), INDEX `Resource_categoryId_status_idx`(`categoryId`,`status`), CONSTRAINT `Resource_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `ResourceCategory`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT `Resource_logoId_fkey` FOREIGN KEY (`logoId`) REFERENCES `Media`(`id`) ON DELETE SET NULL ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
