
"use client";
import { useState } from "react";
type Row={row:number;valid:boolean;warnings:string[];errors:string[];data:Record<string,unknown>};
export function ImportExportClient(){
 const [type,setType]=useState("redirects"),[rows,setRows]=useState<Row[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 async function preview(form:FormData){setBusy(true);setMsg("");try{form.set("type",type);const r=await fetch("/api/admin/import-export/preview",{method:"POST",body:form});const j=await r.json();if(!r.ok)throw new Error(j.error||"Preview failed");setRows(j.rows);setMsg(`${j.summary.valid}/${j.summary.total} valid rows · ${j.summary.invalid} invalid`)}catch(e){setMsg(e instanceof Error?e.message:"Preview failed")}finally{setBusy(false)}}
 async function commit(){setBusy(true);try{const r=await fetch("/api/admin/import-export/commit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,rows})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Import failed");setMsg(`Committed ${j.total} rows · ${j.created} created · ${j.updated} updated`);setRows([])}catch(e){setMsg(e instanceof Error?e.message:"Import failed")}finally{setBusy(false)}}
 return <div className="space-y-6">
  <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Export</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Download current data without changing the database.</p><div className="mt-4 flex flex-wrap gap-2">{["posts","ai-tools","subscribers","redirects","affiliate-links"].flatMap(t=>["csv","json"].map(f=><a key={`${t}-${f}`} href={`/api/admin/import-export/export/${t}?format=${f}`} className="rounded-xl border px-3 py-2 text-sm font-semibold hover:bg-[var(--background-soft)]">{t} · {f.toUpperCase()}</a>))}</div></section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Import</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Preview every row before commit. Commits run inside a transaction.</p><div className="mt-4 grid gap-3 md:grid-cols-[220px_1fr_auto]"><select value={type} onChange={e=>{setType(e.target.value);setRows([])}} className="min-h-12 rounded-xl border px-3">{["redirects","subscribers","ai-tools","posts"].map(x=><option key={x}>{x}</option>)}</select><form action={preview} className="contents"><input type="file" name="file" accept=".csv,.json,application/json,text/csv" required className="min-h-12 rounded-xl border p-2"/><button disabled={busy} className="min-h-12 rounded-xl bg-[var(--primary)] px-5 font-semibold text-white disabled:opacity-50">Preview</button></form></div>{msg&&<p className="mt-3 text-sm">{msg}</p>}
  {rows.length>0&&<><div className="mt-5 max-h-[480px] overflow-auto rounded-xl border" tabIndex={0} role="region" aria-label="Import preview"><table className="w-full min-w-[760px] text-left text-sm"><thead className="sticky top-0 bg-[var(--background-soft)]"><tr><th className="p-3">Row</th><th className="p-3">Status</th><th className="p-3">Data</th><th className="p-3">Issues</th></tr></thead><tbody>{rows.map(r=><tr key={r.row} className="border-t align-top"><td className="p-3">{r.row}</td><td className="p-3 font-semibold">{r.valid?"Valid":"Invalid"}</td><td className="p-3"><pre className="whitespace-pre-wrap text-xs">{JSON.stringify(r.data,null,2)}</pre></td><td className="p-3 text-xs">{[...r.errors,...r.warnings].map((x,i)=><div key={i}>{x}</div>)}</td></tr>)}</tbody></table></div><div className="mt-4 flex justify-end"><button onClick={commit} disabled={busy||rows.every(r=>!r.valid)} className="min-h-12 rounded-xl bg-[var(--primary)] px-5 font-semibold text-white disabled:opacity-50">Commit valid rows</button></div></>}</section>
 </div>
}
