"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
type Note={id:string;note:string;resolvedAt:string|null;createdAt:string;user:{id:string;name:string}};
type Review={reviewer:{name:string}|null;submittedAt:string|null;reviewedAt:string|null;approvedAt:string|null;changesRequestedAt:string|null;reviewNotes:string|null}|null;
export function WorkflowPanel({postId,status,review,notes,canReview,canApprove,canSchedule,canPublish}:{postId:string;status:string;review:Review;notes:Note[];canReview:boolean;canApprove:boolean;canSchedule:boolean;canPublish:boolean}){const router=useRouter();const [note,setNote]=useState("");const [scheduledAt,setScheduledAt]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");async function transition(action:string){setBusy(true);setMessage("");try{const r=await fetch(`/api/admin/editorial/posts/${postId}/transition`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,note:note||null,scheduledAt:action==="schedule"&&scheduledAt?new Date(scheduledAt).toISOString():null})});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||"Workflow update failed");setNote("");setMessage("Workflow updated.");router.refresh()}catch(e){setMessage(e instanceof Error?e.message:"Workflow update failed")}finally{setBusy(false)}}async function addNote(){if(!note.trim())return;setBusy(true);try{const r=await fetch(`/api/admin/editorial/posts/${postId}/notes`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({note})});if(!r.ok)throw new Error((await r.json())?.error?.message||"Note failed");setNote("");router.refresh()}finally{setBusy(false)}}async function noteAction(id:string,method:"PATCH"|"DELETE"){await fetch(`/api/admin/editorial/notes/${id}`,{method});router.refresh()}async function preview(){const r=await fetch(`/api/admin/editorial/posts/${postId}/preview-token`,{method:"POST"});const j=await r.json();if(!r.ok){setMessage(j?.error?.message||"Preview link failed");return}window.open(j.data.url,"_blank","noopener,noreferrer")}
return <section className="space-y-4 rounded-2xl border border-[var(--border)] bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">Editorial workflow</h3><p className="text-sm text-[var(--muted)]">Current status: <strong>{status.replaceAll("_"," ")}</strong></p></div><Button type="button" variant="secondary" onClick={preview}>Secure preview</Button></div>{review&&<div className="rounded-xl bg-slate-50 p-3 text-sm"><p>Reviewer: {review.reviewer?.name??"Not assigned"}</p>{review.reviewNotes&&<p className="mt-1 text-[var(--muted)]">{review.reviewNotes}</p>}</div>}<Textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="Private editorial note or review message"/><div className="flex flex-wrap gap-2"><Button type="button" variant="secondary" disabled={busy} onClick={addNote}>Add private note</Button>{["DRAFT","CHANGES_REQUESTED","REVIEW"].includes(status)&&<Button type="button" disabled={busy} onClick={()=>transition("submit")}>Submit for review</Button>}{canReview&&["IN_REVIEW","REVIEW","APPROVED"].includes(status)&&<Button type="button" variant="secondary" disabled={busy} onClick={()=>transition("request_changes")}>Request changes</Button>}{canApprove&&["IN_REVIEW","REVIEW"].includes(status)&&<Button type="button" disabled={busy} onClick={()=>transition("approve")}>Approve</Button>}</div>{canSchedule&&status==="APPROVED"&&<div className="grid gap-2 md:grid-cols-[1fr_auto]"><Input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/><Button type="button" disabled={!scheduledAt||busy} onClick={()=>transition("schedule")}>Schedule</Button></div>}{canPublish&&["APPROVED","SCHEDULED"].includes(status)&&<Button type="button" disabled={busy} onClick={()=>transition("publish")}>Publish now</Button>}{message&&<p className="text-sm text-[var(--muted)]">{message}</p>}<div className="space-y-2"><h4 className="text-sm font-semibold">Private notes</h4>{notes.length===0&&<p className="text-sm text-[var(--muted)]">No editorial notes yet.</p>}{notes.map(n=><article key={n.id} className={`rounded-xl border p-3 text-sm ${n.resolvedAt?"opacity-60":""}`}><div className="flex items-start justify-between gap-3"><div><strong>{n.user.name}</strong><p className="mt-1 whitespace-pre-wrap">{n.note}</p></div><div className="flex gap-1"><button type="button" className="text-xs text-blue-700 underline" onClick={()=>noteAction(n.id,"PATCH")}>{n.resolvedAt?"Reopen":"Resolve"}</button><button type="button" className="text-xs text-red-700 underline" onClick={()=>noteAction(n.id,"DELETE")}>Delete</button></div></div></article>)}</div></section>}
