import { randomBytes,createHash } from "node:crypto"; import { prisma } from "@/lib/db/prisma"; import { env } from "@/lib/env"; import { sendMail } from "@/services/email/mailer"; import { emailTemplateService } from "@/services/email/template.service"; import {emitWebhook} from "@/services/webhooks/webhook.service";
const h=(v:string)=>createHash("sha256").update(v).digest("hex");
async function token(subscriberId:string,purpose:"CONFIRM"|"UNSUBSCRIBE",hours:number){const raw=randomBytes(32).toString("hex");await prisma.newsletterToken.create({data:{subscriberId,purpose,tokenHash:h(raw),expiresAt:new Date(Date.now()+hours*3600000)}});return raw}
export const newsletterService={
 async subscribe(email:string,name?:string,source="website",segmentSlugs:string[]=[]){email=email.toLowerCase();const existing=await prisma.newsletterSubscriber.findUnique({where:{email},select:{id:true}});const cfg=await prisma.siteSetting.findUnique({where:{key:"newsletter.confirmationRequired"}});const needsConfirm=cfg?.value!==false;const s=await prisma.newsletterSubscriber.upsert({where:{email},update:{name:name||undefined,status:needsConfirm?"PENDING":"ACTIVE",confirmedAt:needsConfirm?undefined:new Date(),unsubscribedAt:null,source},create:{email,name,status:needsConfirm?"PENDING":"ACTIVE",confirmedAt:needsConfirm?null:new Date(),source}});if(segmentSlugs.length){const segs=await prisma.newsletterSegment.findMany({where:{slug:{in:segmentSlugs},active:true},select:{id:true}});await prisma.newsletterSubscriberSegment.deleteMany({where:{subscriberId:s.id}});if(segs.length)await prisma.newsletterSubscriberSegment.createMany({data:segs.map(x=>({subscriberId:s.id,segmentId:x.id}))});}if(!existing)void emitWebhook("subscriber.created",{id:s.id,email:s.email,source:s.source,status:s.status});if(!needsConfirm)return {subscriber:s,confirmationRequired:false};await prisma.newsletterToken.deleteMany({where:{subscriberId:s.id,purpose:"CONFIRM",usedAt:null}});const raw=await token(s.id,"CONFIRM",24);const confirmationUrl=`${env.SITE_URL}/newsletter/confirm?token=${raw}`;try{await emailTemplateService.send("newsletter.confirmation",email,{name:name||"there",confirmationUrl})}catch{await sendMail({to:email,subject:"Confirm your PushStream subscription",text:`Confirm your subscription: ${confirmationUrl}`})}return {subscriber:s,confirmationRequired:true}},
 async confirm(raw:string){const t=await prisma.newsletterToken.findUnique({where:{tokenHash:h(raw)}});if(!t||t.purpose!=="CONFIRM"||t.usedAt||t.expiresAt<new Date())return false;await prisma.$transaction([prisma.newsletterToken.update({where:{id:t.id},data:{usedAt:new Date()}}),prisma.newsletterSubscriber.update({where:{id:t.subscriberId},data:{status:"ACTIVE",confirmedAt:new Date(),unsubscribedAt:null}})]);return true},
 async createUnsubscribe(email:string){const s=await prisma.newsletterSubscriber.findUnique({where:{email:email.toLowerCase()}});if(!s)return;const raw=await token(s.id,"UNSUBSCRIBE",168);await sendMail({to:s.email,subject:"Unsubscribe from PushStream",text:`Unsubscribe: ${env.SITE_URL}/newsletter/unsubscribe?token=${raw}`})},
 async unsubscribe(raw:string){const t=await prisma.newsletterToken.findUnique({where:{tokenHash:h(raw)}});if(!t||t.purpose!=="UNSUBSCRIBE"||t.usedAt||t.expiresAt<new Date())return false;await prisma.$transaction([prisma.newsletterToken.update({where:{id:t.id},data:{usedAt:new Date()}}),prisma.newsletterSubscriber.update({where:{id:t.subscriberId},data:{status:"UNSUBSCRIBED",unsubscribedAt:new Date()}})]);return true}
};
