import { randomBytes } from "node:crypto";
import { prisma } from "@/lib/db/prisma";
import type { CurrentSession } from "@/lib/auth/session";
import { hasPermission } from "@/lib/auth/permissions";
import { sha256 } from "@/lib/security/crypto";
import { editorialNoteSchema, editorialTransitionSchema, calendarRescheduleSchema } from "@/lib/validation/cms";
import { auditService } from "@/services/audit/audit.service";
import { AppError } from "@/lib/errors/app-error";
import {emitWebhook} from "@/services/webhooks/webhook.service";

const LOCK_MINUTES = 3;
function can(session:CurrentSession,key:string){return hasPermission(session.user.permissions,key)}
function requireOwnerOr(session:CurrentSession,ownerId:string,key:string){if(session.user.id!==ownerId&&!can(session,key))throw new AppError("FORBIDDEN","You cannot modify this post.",403)}
async function notify(userId:string|undefined,type:"EDITORIAL_SUBMITTED"|"EDITORIAL_CHANGES_REQUESTED"|"EDITORIAL_APPROVED"|"EDITORIAL_SCHEDULED"|"EDITORIAL_PUBLISHED",title:string,message:string){if(!userId)return;await prisma.notification.create({data:{userId,type,title,message}}).catch(()=>undefined)}

export const workflowService={
 async details(postId:string,session:CurrentSession){const post=await prisma.post.findUnique({where:{id:postId},include:{editorialReview:{include:{reviewer:{select:{id:true,name:true,email:true}}}},editorialNotes:{include:{user:{select:{id:true,name:true}}},orderBy:{createdAt:"desc"},take:100},editorLock:{include:{user:{select:{id:true,name:true,email:true}}}}}});if(!post)return null;requireOwnerOr(session,post.authorId,"posts.edit");const lock=post.editorLock&&post.editorLock.expiresAt>new Date()?post.editorLock:null;return {...post,editorLock:lock};},
 async transition(postId:string,raw:unknown,session:CurrentSession){const v=editorialTransitionSchema.parse(raw);const post=await prisma.post.findUnique({where:{id:postId},include:{editorialReview:true}});if(!post)throw new AppError("NOT_FOUND","Post not found.",404);const now=new Date();
  if(v.action==="submit"){requireOwnerOr(session,post.authorId,"workflow.submit");if(!["DRAFT","CHANGES_REQUESTED","REVIEW"].includes(post.status))throw new AppError("INVALID_STATE","Only drafts or change-requested posts can be submitted.",409);const result=await prisma.$transaction(async tx=>{const updated=await tx.post.update({where:{id:postId},data:{status:"IN_REVIEW"}});await tx.editorialReview.upsert({where:{postId},create:{postId,submittedAt:now,reviewNotes:v.note||null},update:{submittedAt:now,reviewedAt:null,approvedAt:null,changesRequestedAt:null,reviewNotes:v.note||null}});return updated});await notify(undefined,"EDITORIAL_SUBMITTED","Article submitted",`${post.title} was submitted for review.`);await auditService.record({userId:session.user.id,action:"workflow.submit",entityType:"Post",entityId:postId});return result;}
  if(v.action==="request_changes"){if(!can(session,"workflow.review"))throw new AppError("FORBIDDEN","Review permission required.",403);if(!["IN_REVIEW","APPROVED","REVIEW"].includes(post.status))throw new AppError("INVALID_STATE","This post is not awaiting editorial review.",409);const result=await prisma.$transaction(async tx=>{const updated=await tx.post.update({where:{id:postId},data:{status:"CHANGES_REQUESTED"}});await tx.editorialReview.upsert({where:{postId},create:{postId,reviewerId:session.user.id,submittedAt:now,reviewedAt:now,changesRequestedAt:now,reviewNotes:v.note||null},update:{reviewerId:session.user.id,reviewedAt:now,changesRequestedAt:now,approvedAt:null,reviewNotes:v.note||null}});return updated});await notify(post.authorId,"EDITORIAL_CHANGES_REQUESTED","Changes requested",v.note||`Changes were requested for ${post.title}.`);await auditService.record({userId:session.user.id,action:"workflow.request_changes",entityType:"Post",entityId:postId,metadata:{note:v.note||null}});return result;}
  if(v.action==="approve"){if(!can(session,"workflow.approve"))throw new AppError("FORBIDDEN","Approval permission required.",403);if(!["IN_REVIEW","REVIEW"].includes(post.status))throw new AppError("INVALID_STATE","Only posts in review can be approved.",409);const result=await prisma.$transaction(async tx=>{const updated=await tx.post.update({where:{id:postId},data:{status:"APPROVED"}});await tx.editorialReview.upsert({where:{postId},create:{postId,reviewerId:session.user.id,submittedAt:now,reviewedAt:now,approvedAt:now,reviewNotes:v.note||null},update:{reviewerId:session.user.id,reviewedAt:now,approvedAt:now,changesRequestedAt:null,reviewNotes:v.note||null}});return updated});await notify(post.authorId,"EDITORIAL_APPROVED","Article approved",v.note||`${post.title} was approved.`);await auditService.record({userId:session.user.id,action:"workflow.approve",entityType:"Post",entityId:postId});return result;}
  if(v.action==="schedule"){if(!can(session,"workflow.schedule")&&!can(session,"posts.publish"))throw new AppError("FORBIDDEN","Scheduling permission required.",403);if(!v.scheduledAt)throw new AppError("VALIDATION_ERROR","Scheduled date is required.",400);const date=new Date(v.scheduledAt);if(date<=now)throw new AppError("VALIDATION_ERROR","Scheduled date must be in the future.",400);const result=await prisma.post.update({where:{id:postId},data:{status:"SCHEDULED",scheduledAt:date}});await notify(post.authorId,"EDITORIAL_SCHEDULED","Article scheduled",`${post.title} is scheduled for ${date.toISOString()}.`);await auditService.record({userId:session.user.id,action:"workflow.schedule",entityType:"Post",entityId:postId,metadata:{scheduledAt:date.toISOString()}});return result;}
  if(v.action==="publish"){if(!can(session,"posts.publish"))throw new AppError("FORBIDDEN","Publish permission required.",403);const result=await prisma.post.update({where:{id:postId},data:{status:"PUBLISHED",publishedAt:post.publishedAt??now,scheduledAt:null,lastMeaningfulUpdateAt:now}});await notify(post.authorId,"EDITORIAL_PUBLISHED","Article published",`${post.title} was published.`);await auditService.record({userId:session.user.id,action:"workflow.publish",entityType:"Post",entityId:postId});void emitWebhook("post.published",{id:result.id,slug:result.slug,title:result.title,publishedAt:result.publishedAt?.toISOString()??null});return result;}
  if(v.action==="archive"){if(!can(session,"posts.publish"))throw new AppError("FORBIDDEN","Publish permission required.",403);return prisma.post.update({where:{id:postId},data:{status:"ARCHIVED"}})}
  throw new AppError("VALIDATION_ERROR","Unsupported workflow action.",400);
 },
 async addNote(postId:string,raw:unknown,session:CurrentSession){const v=editorialNoteSchema.parse(raw);const post=await prisma.post.findUnique({where:{id:postId},select:{authorId:true}});if(!post)throw new AppError("NOT_FOUND","Post not found.",404);requireOwnerOr(session,post.authorId,"editorialNotes.manage");const note=await prisma.editorialNote.create({data:{postId,userId:session.user.id,note:v.note}});await auditService.record({userId:session.user.id,action:"editorial_note.create",entityType:"Post",entityId:postId});return note;},
 async updateNote(noteId:string,raw:unknown,session:CurrentSession){const v=editorialNoteSchema.parse(raw);const note=await prisma.editorialNote.findUnique({where:{id:noteId}});if(!note)throw new AppError("NOT_FOUND","Note not found.",404);if(note.userId!==session.user.id&&!can(session,"workflow.review"))throw new AppError("FORBIDDEN","Cannot edit this note.",403);return prisma.editorialNote.update({where:{id:noteId},data:{note:v.note}})},
 async resolveNote(noteId:string,session:CurrentSession){const note=await prisma.editorialNote.findUnique({where:{id:noteId}});if(!note)throw new AppError("NOT_FOUND","Note not found.",404);if(note.userId!==session.user.id&&!can(session,"workflow.review"))throw new AppError("FORBIDDEN","Cannot resolve this note.",403);return prisma.editorialNote.update({where:{id:noteId},data:{resolvedAt:note.resolvedAt?null:new Date()}})},
 async deleteNote(noteId:string,session:CurrentSession){const note=await prisma.editorialNote.findUnique({where:{id:noteId}});if(!note)return null;if(note.userId!==session.user.id&&!can(session,"workflow.review"))throw new AppError("FORBIDDEN","Cannot delete this note.",403);await prisma.editorialNote.delete({where:{id:noteId}});return {id:noteId}},
 async acquireLock(postId:string,session:CurrentSession,override=false){const post=await prisma.post.findUnique({where:{id:postId},select:{authorId:true}});if(!post)throw new AppError("NOT_FOUND","Post not found.",404);requireOwnerOr(session,post.authorId,"posts.edit");const existing=await prisma.postEditorLock.findUnique({where:{postId},include:{user:{select:{id:true,name:true,email:true}}}});const now=new Date();if(existing&&existing.expiresAt>now&&existing.userId!==session.user.id&&!(override&&can(session,"workflow.overrideLock")))return {acquired:false,lockedBy:existing.user,expiresAt:existing.expiresAt};const expiresAt=new Date(now.getTime()+LOCK_MINUTES*60_000);const lock=await prisma.postEditorLock.upsert({where:{postId},create:{postId,userId:session.user.id,expiresAt,heartbeatAt:now},update:{userId:session.user.id,expiresAt,heartbeatAt:now,acquiredAt:existing?.userId===session.user.id?existing.acquiredAt:now},include:{user:{select:{id:true,name:true,email:true}}}});return {acquired:true,lockedBy:lock.user,expiresAt:lock.expiresAt}},
 async releaseLock(postId:string,session:CurrentSession){const lock=await prisma.postEditorLock.findUnique({where:{postId}});if(!lock)return {released:true};if(lock.userId!==session.user.id&&!can(session,"workflow.overrideLock"))throw new AppError("FORBIDDEN","Cannot release another editor's lock.",403);await prisma.postEditorLock.delete({where:{postId}});return {released:true}},
 async createPreview(postId:string,session:CurrentSession){const post=await prisma.post.findUnique({where:{id:postId},select:{authorId:true,slug:true}});if(!post)throw new AppError("NOT_FOUND","Post not found.",404);requireOwnerOr(session,post.authorId,"posts.edit");const raw=randomBytes(32).toString("base64url");const expiresAt=new Date(Date.now()+24*60*60_000);await prisma.previewToken.create({data:{postId,createdById:session.user.id,tokenHash:sha256(raw),expiresAt}});return {token:raw,expiresAt,url:`/preview/post/${raw}`}},
 async reschedule(postId:string,raw:unknown,session:CurrentSession){if(!can(session,"calendar.manage")&&!can(session,"workflow.schedule"))throw new AppError("FORBIDDEN","Calendar manage permission required.",403);const v=calendarRescheduleSchema.parse(raw);const post=await prisma.post.findUnique({where:{id:postId}});if(!post)throw new AppError("NOT_FOUND","Post not found.",404);if(post.status!=="SCHEDULED")throw new AppError("INVALID_STATE","Only scheduled posts can be moved on the calendar.",409);const date=new Date(v.scheduledAt);if(date<=new Date())throw new AppError("VALIDATION_ERROR","Scheduled date must be in the future.",400);const updated=await prisma.post.update({where:{id:postId},data:{scheduledAt:date}});await auditService.record({userId:session.user.id,action:"calendar.reschedule",entityType:"Post",entityId:postId,metadata:{scheduledAt:date.toISOString()}});return updated;},
 async calendar(args:{start:Date;end:Date;authorId?:string;categoryId?:string;status?:string},session:CurrentSession){const authorScope=session.user.roles.includes("AUTHOR")&&!can(session,"workflow.review")?session.user.id:args.authorId;return prisma.post.findMany({where:{deletedAt:null,...(authorScope?{authorId:authorScope}:{}),...(args.categoryId?{categoryId:args.categoryId}:{}),...(args.status?{status:args.status as never}:{}),OR:[{scheduledAt:{gte:args.start,lte:args.end}},{publishedAt:{gte:args.start,lte:args.end}},{updatedAt:{gte:args.start,lte:args.end}}]},select:{id:true,title:true,status:true,scheduledAt:true,publishedAt:true,updatedAt:true,author:{select:{id:true,name:true}},category:{select:{id:true,name:true}}},orderBy:[{scheduledAt:"asc"},{updatedAt:"desc"}],take:500})},
 async staleContent(months:number){const before=new Date();before.setMonth(before.getMonth()-months);return prisma.post.findMany({where:{status:"PUBLISHED",deletedAt:null,updatedAt:{lt:before}},select:{id:true,title:true,slug:true,updatedAt:true,reviewDueAt:true,category:{select:{name:true}}},orderBy:{updatedAt:"asc"},take:500})}
};
