import { z } from "zod";
const nullableText = z.string().trim().max(2000).optional().nullable();
export const postInputSchema = z.object({
  title: z.string().trim().min(1).max(240), slug: z.string().trim().max(180).optional(), subtitle: z.string().trim().max(300).optional().nullable(), excerpt: z.string().trim().max(1000).optional().nullable(),
  content: z.unknown().default({ type: "doc", content: [] }), authorId: z.string().min(1), categoryId: z.string().optional().nullable(), tagIds: z.array(z.string()).default([]), status: z.enum(["DRAFT","REVIEW","IN_REVIEW","CHANGES_REQUESTED","APPROVED","SCHEDULED","PUBLISHED","ARCHIVED","TRASH"]).default("DRAFT"),
  scheduledAt: z.string().datetime().optional().nullable(), seoTitle: z.string().trim().max(240).optional().nullable(), seoDescription: z.string().trim().max(500).optional().nullable(), canonicalUrl: z.string().url().optional().nullable().or(z.literal("")), focusKeyword: nullableText,
  robotsIndex: z.boolean().default(true), robotsFollow: z.boolean().default(true), ogTitle: z.string().max(240).optional().nullable(), ogDescription: z.string().max(500).optional().nullable(), schemaType: z.string().max(80).default("BlogPosting"),
  reviewDueAt: z.string().datetime().optional().nullable(),
  tutorialDifficulty: z.enum(["BEGINNER","INTERMEDIATE","ADVANCED"]).optional().nullable(),
  tutorialEstimatedMinutes: z.coerce.number().int().min(1).max(10080).optional().nullable(),
  tutorialRequirements: z.string().trim().max(5000).optional().nullable(),
  tutorialToolsNeeded: z.string().trim().max(5000).optional().nullable(),
  tutorialPrerequisites: z.string().trim().max(5000).optional().nullable(),
  isFeatured: z.boolean().default(false), isTrending: z.boolean().default(false), isSponsored: z.boolean().default(false), sponsorName:z.string().trim().max(160).optional().nullable(), sponsorUrl:z.string().url().optional().nullable().or(z.literal("")), sponsorDisclosureText:z.string().trim().max(2000).optional().nullable(), isAffiliate: z.boolean().default(false), allowComments: z.boolean().default(true), tableOfContentsEnabled: z.boolean().default(true), featuredImageId: z.string().optional().nullable(), featuredImageAlt: z.string().max(300).optional().nullable(), ogImageId: z.string().optional().nullable(), twitterImageId: z.string().optional().nullable()
}).superRefine((value, ctx) => { if (value.status === "SCHEDULED") { if (!value.scheduledAt || new Date(value.scheduledAt) <= new Date()) ctx.addIssue({ code: "custom", path: ["scheduledAt"], message: "Scheduled publish time must be in the future." }); } });
export const categoryInputSchema = z.object({ name:z.string().trim().min(1).max(120), slug:z.string().max(180).optional(), description:nullableText, icon:z.string().max(120).optional().nullable(), parentId:z.string().optional().nullable(), seoTitle:z.string().max(240).optional().nullable(), seoDescription:z.string().max(500).optional().nullable(), robotsIndex:z.boolean().default(true), featured:z.boolean().default(false), sortOrder:z.coerce.number().int().min(0).max(99999).default(0) });
export const tagInputSchema = z.object({ name:z.string().trim().min(1).max(120), slug:z.string().max(180).optional(), description:nullableText, seoTitle:z.string().max(240).optional().nullable(), seoDescription:z.string().max(500).optional().nullable() });
export const pageInputSchema = z.object({ title:z.string().trim().min(1).max(240), slug:z.string().max(180).optional(), content:z.unknown().default({type:"doc",content:[]}), status:z.enum(["DRAFT","REVIEW","SCHEDULED","PUBLISHED","ARCHIVED","TRASH"]).default("DRAFT"), seoTitle:z.string().max(240).optional().nullable(), seoDescription:z.string().max(500).optional().nullable(), robotsIndex:z.boolean().default(true) });
export const authorInputSchema = z.object({ userId:z.string().min(1), slug:z.string().max(180).optional(), jobTitle:z.string().max(160).optional().nullable(), shortBio:z.string().max(500).optional().nullable(), fullBio:z.string().max(10000).optional().nullable(), website:z.string().url().optional().nullable().or(z.literal("")), publicEmail:z.string().email().optional().nullable().or(z.literal("")), facebook:z.string().url().optional().nullable().or(z.literal("")), xTwitter:z.string().url().optional().nullable().or(z.literal("")), linkedin:z.string().url().optional().nullable().or(z.literal("")), youtube:z.string().url().optional().nullable().or(z.literal("")), instagram:z.string().url().optional().nullable().or(z.literal("")), github:z.string().url().optional().nullable().or(z.literal("")), expertise:z.array(z.string().trim().min(1).max(80)).max(30).default([]), seoTitle:z.string().max(240).optional().nullable(), seoDescription:z.string().max(500).optional().nullable() });

export const editorialTransitionSchema = z.object({ action:z.enum(["submit","request_changes","approve","schedule","publish","archive"]), note:z.string().trim().max(5000).optional().nullable(), scheduledAt:z.string().datetime().optional().nullable() });
export const editorialNoteSchema = z.object({ note:z.string().trim().min(1).max(5000) });
export const calendarRescheduleSchema = z.object({ scheduledAt:z.string().datetime() });
