ALTER TABLE `Session` ADD COLUMN `deviceDescription` VARCHAR(180) NULL;
CREATE TABLE `TwoFactorCredential` (`id` VARCHAR(191) NOT NULL,`userId` VARCHAR(191) NOT NULL,`secretEncrypted` TEXT NOT NULL,`enabled` BOOLEAN NOT NULL DEFAULT false,`verifiedAt` DATETIME(3) NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),`updatedAt` DATETIME(3) NOT NULL,UNIQUE INDEX `TwoFactorCredential_userId_key`(`userId`),PRIMARY KEY (`id`));
CREATE TABLE `TwoFactorBackupCode` (`id` VARCHAR(191) NOT NULL,`credentialId` VARCHAR(191) NOT NULL,`codeHash` VARCHAR(64) NOT NULL,`usedAt` DATETIME(3) NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),UNIQUE INDEX `TwoFactorBackupCode_credentialId_codeHash_key`(`credentialId`,`codeHash`),INDEX `TwoFactorBackupCode_credentialId_usedAt_idx`(`credentialId`,`usedAt`),PRIMARY KEY (`id`));
CREATE TABLE `TwoFactorChallenge` (`id` VARCHAR(191) NOT NULL,`userId` VARCHAR(191) NOT NULL,`tokenHash` VARCHAR(64) NOT NULL,`remember` BOOLEAN NOT NULL DEFAULT false,`expiresAt` DATETIME(3) NOT NULL,`consumedAt` DATETIME(3) NULL,`ipHash` VARCHAR(64) NULL,`userAgent` VARCHAR(500) NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),UNIQUE INDEX `TwoFactorChallenge_tokenHash_key`(`tokenHash`),INDEX `TwoFactorChallenge_userId_expiresAt_idx`(`userId`,`expiresAt`),PRIMARY KEY (`id`));
CREATE TABLE `SecurityEvent` (`id` VARCHAR(191) NOT NULL,`userId` VARCHAR(191) NULL,`type` VARCHAR(120) NOT NULL,`severity` ENUM('INFO','WARNING','HIGH','CRITICAL') NOT NULL DEFAULT 'INFO',`summary` VARCHAR(500) NOT NULL,`metadata` JSON NULL,`ipHash` VARCHAR(64) NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX `SecurityEvent_severity_createdAt_idx`(`severity`,`createdAt`),INDEX `SecurityEvent_type_createdAt_idx`(`type`,`createdAt`),INDEX `SecurityEvent_userId_createdAt_idx`(`userId`,`createdAt`),PRIMARY KEY (`id`));
ALTER TABLE `TwoFactorCredential` ADD CONSTRAINT `TwoFactorCredential_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `TwoFactorBackupCode` ADD CONSTRAINT `TwoFactorBackupCode_credentialId_fkey` FOREIGN KEY (`credentialId`) REFERENCES `TwoFactorCredential`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `TwoFactorChallenge` ADD CONSTRAINT `TwoFactorChallenge_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `SecurityEvent` ADD CONSTRAINT `SecurityEvent_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
