import { prisma } from "@/lib/db/prisma";
import type {JobQueue,QueueInput,SupportedJobType} from "@/lib/jobs/types";
import {postService} from "@/services/cms/post.service";
import {aggregateDay} from "./analytics-aggregation.service";
import {deliverWebhook} from "@/services/webhooks/webhook.service";

const leaseMs=10*60_000;
const safeError=(e:unknown)=>String(e instanceof Error?e.message:e).replace(/(mysql:\/\/)[^@\s]+@/gi,"$1[redacted]@").replace(/(token|secret|password|authorization)\s*[=:]\s*[^\s,;]+/gi,"$1=[redacted]").slice(0,2000);
async function run(type:SupportedJobType,payload:unknown){if(type==="SCHEDULED_PUBLISH")return postService.publishScheduled();if(type==="ANALYTICS_AGGREGATE"){const p=(payload||{}) as {date?:string};return aggregateDay(p.date?new Date(p.date):undefined)}if(type==="WEBHOOK_DELIVERY"){const p=(payload||{}) as {deliveryId?:string};if(!p.deliveryId)throw new Error("Webhook delivery id required.");return deliverWebhook(p.deliveryId)}if(type==="MAINTENANCE"){const stale=new Date(Date.now()-leaseMs);const now=new Date();const retention=new Date(Date.now()-30*86_400_000);const [unlocked,locks,tokens,ads,purged]=await prisma.$transaction([prisma.backgroundJob.updateMany({where:{status:"RUNNING",lockedAt:{lt:stale}},data:{status:"PENDING",lockedAt:null,lockedBy:null}}),prisma.postEditorLock.deleteMany({where:{expiresAt:{lt:now}}}),prisma.previewToken.deleteMany({where:{expiresAt:{lt:now}}}),prisma.adSlot.updateMany({where:{enabled:true,endAt:{lt:now}},data:{enabled:false}}),prisma.backgroundJob.deleteMany({where:{status:"COMPLETED",completedAt:{lt:retention}}})]);return {releasedStaleJobs:unlocked.count,expiredEditorLocks:locks.count,expiredPreviewTokens:tokens.count,expiredAds:ads.count,purgedCompletedJobs:purged.count}}throw new Error(`Unsupported job type ${type}`)}
export const databaseJobQueue:JobQueue={
 async enqueue(input:QueueInput){if(input.dedupeKey){const found=await prisma.backgroundJob.findUnique({where:{dedupeKey:input.dedupeKey},select:{id:true}});if(found)return found}return prisma.backgroundJob.create({data:{type:input.type,payload:(input.payload??{}) as never,dedupeKey:input.dedupeKey,runAt:input.runAt??new Date(),priority:input.priority??0,maxAttempts:input.maxAttempts??5},select:{id:true}})},
 async processBatch({workerId,limit=10}){const safe=Math.min(50,Math.max(1,limit));const stale=new Date(Date.now()-leaseMs);await prisma.backgroundJob.updateMany({where:{status:"RUNNING",lockedAt:{lt:stale}},data:{status:"PENDING",lockedAt:null,lockedBy:null}});const candidates=await prisma.backgroundJob.findMany({where:{status:"PENDING",runAt:{lte:new Date()}},orderBy:[{priority:"desc"},{runAt:"asc"}],take:safe*2,select:{id:true}});let claimed=0,completed=0,failed=0;
  for(const c of candidates){if(claimed>=safe)break;const now=new Date();const lock=await prisma.backgroundJob.updateMany({where:{id:c.id,status:"PENDING"},data:{status:"RUNNING",lockedAt:now,lockedBy:workerId,attempts:{increment:1}}});if(lock.count!==1)continue;claimed++;const job=await prisma.backgroundJob.findUnique({where:{id:c.id}});if(!job)continue;const attempt=job.attempts;await prisma.jobAttempt.create({data:{jobId:job.id,attempt,workerId}});
   try{await run(job.type as SupportedJobType,job.payload);await prisma.$transaction([prisma.backgroundJob.update({where:{id:job.id},data:{status:"COMPLETED",completedAt:new Date(),lockedAt:null,lockedBy:null,lastError:null}}),prisma.jobAttempt.update({where:{jobId_attempt:{jobId:job.id,attempt}},data:{finishedAt:new Date(),succeeded:true}})]);completed++;}
   catch(e){const error=safeError(e);const retry=attempt<job.maxAttempts;const delay=Math.min(60,2**Math.min(attempt,6))*60_000;await prisma.$transaction([prisma.backgroundJob.update({where:{id:job.id},data:{status:retry?"PENDING":"FAILED",runAt:retry?new Date(Date.now()+delay):job.runAt,lockedAt:null,lockedBy:null,lastError:error}}),prisma.jobAttempt.update({where:{jobId_attempt:{jobId:job.id,attempt}},data:{finishedAt:new Date(),succeeded:false,error}})]);failed++;}
  }return {claimed,completed,failed};
 }};
export async function enqueueRecurringJobs(){const now=new Date();const yesterday=new Date(now.getTime()-86_400_000).toISOString().slice(0,10);const today=now.toISOString().slice(0,10);const hour=now.toISOString().slice(0,13);const minute=now.toISOString().slice(0,16);await Promise.all([databaseJobQueue.enqueue({type:"SCHEDULED_PUBLISH",dedupeKey:`publish:${minute}`,priority:100,maxAttempts:3}),databaseJobQueue.enqueue({type:"ANALYTICS_AGGREGATE",payload:{date:yesterday},dedupeKey:`analytics:${yesterday}`,priority:30,maxAttempts:4}),databaseJobQueue.enqueue({type:"ANALYTICS_AGGREGATE",payload:{date:today},dedupeKey:`analytics:${today}:${hour}`,priority:20,maxAttempts:3}),databaseJobQueue.enqueue({type:"MAINTENANCE",dedupeKey:`maintenance:${now.toISOString().slice(0,13)}`,priority:5,maxAttempts:2})]);}
