import { prisma } from "@/lib/db/prisma";
const DAY=86_400_000;
function startOfDay(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);return x}
function hostOf(value?:string|null){if(!value)return"Direct / unknown";try{return new URL(value).hostname.replace(/^www\./,"")}catch{return"Other"}}
function range(days=30,fromRaw?:string,toRaw?:string){if(fromRaw&&toRaw){const from=startOfDay(new Date(fromRaw));const to=startOfDay(new Date(toRaw));to.setDate(to.getDate()+1);if(Number.isFinite(+from)&&Number.isFinite(+to)&&to>from&&to.getTime()-from.getTime()<=366*DAY)return{from,to,days:Math.ceil((+to-+from)/DAY)}}const safe=[1,7,30,90].includes(days)?days:30;const from=startOfDay(new Date(Date.now()-(safe-1)*DAY));return{from,to:new Date(),days:safe}}
export const analyticsService={
 async overview(days=30,fromRaw?:string,toRaw?:string){const r=range(days,fromRaw,toRaw);const [daily,rawViews,topPosts]=await Promise.all([prisma.dailyContentStat.findMany({where:{entityType:"POST",date:{gte:r.from,lt:r.to}},orderBy:{date:"asc"}}),prisma.postView.findMany({where:{viewedAt:{gte:r.from,lt:r.to}},select:{referrer:true,sessionHash:true,deviceGroup:true},orderBy:{viewedAt:"desc"},take:50000}),prisma.post.findMany({where:{status:"PUBLISHED",deletedAt:null},select:{id:true,title:true,slug:true,views:true,category:{select:{name:true}}},orderBy:{views:"desc"},take:10})]);const byDate=new Map<string,number>();for(const row of daily){const k=row.date.toISOString().slice(0,10);byDate.set(k,(byDate.get(k)||0)+row.views)}const sources=new Map<string,number>();const devices=new Map<string,number>();const sessions=new Set<string>();for(const v of rawViews){const h=hostOf(v.referrer);sources.set(h,(sources.get(h)||0)+1);const d=v.deviceGroup||"Unknown";devices.set(d,(devices.get(d)||0)+1);if(v.sessionHash)sessions.add(v.sessionHash)}return{days:r.days,totalViews:daily.reduce((n,x)=>n+x.views,0),approximateSessions:sessions.size,series:Array.from({length:r.days},(_,i)=>{const d=new Date(r.from.getTime()+i*DAY),date=d.toISOString().slice(0,10);return{date,views:byDate.get(date)||0}}),sources:[...sources].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([source,views])=>({source,views})),devices:[...devices].sort((a,b)=>b[1]-a[1]).map(([device,views])=>({device,views})),topPosts};},
 async contentPerformance(days=30){const now=new Date(),from=startOfDay(new Date(Date.now()-(days-1)*DAY)),recent=startOfDay(new Date(Date.now()-7*DAY)),previous=startOfDay(new Date(Date.now()-14*DAY));const [stats,recentStats,previousStats,affiliate]=await Promise.all([prisma.dailyContentStat.groupBy({by:["entityId"],where:{entityType:"POST",date:{gte:from}},_sum:{views:true,affiliateClicks:true,searchClicks:true}}),prisma.dailyContentStat.groupBy({by:["entityId"],where:{entityType:"POST",date:{gte:recent,lte:now}},_sum:{views:true}}),prisma.dailyContentStat.groupBy({by:["entityId"],where:{entityType:"POST",date:{gte:previous,lt:recent}},_sum:{views:true}}),prisma.dailyContentStat.groupBy({by:["entityId"],where:{entityType:"POST",date:{gte:from},affiliateClicks:{gt:0}},_sum:{affiliateClicks:true}})]);const ids=[...new Set([...stats,...recentStats,...previousStats,...affiliate].map(x=>x.entityId))];const posts=ids.length?await prisma.post.findMany({where:{id:{in:ids},status:"PUBLISHED",deletedAt:null},select:{id:true,title:true,slug:true,publishedAt:true,category:{select:{name:true}}}}):[];const map=new Map(posts.map(p=>[p.id,p]));const rows=stats.map(s=>({post:map.get(s.entityId),views:s._sum.views||0,affiliateClicks:s._sum.affiliateClicks||0,searchClicks:s._sum.searchClicks||0})).filter(x=>x.post).sort((a,b)=>b.views-a.views);const recentMap=new Map(recentStats.map(x=>[x.entityId,x._sum.views||0])),prevMap=new Map(previousStats.map(x=>[x.entityId,x._sum.views||0]));const growing=ids.map(id=>({post:map.get(id),recent:recentMap.get(id)||0,previous:prevMap.get(id)||0,growth:(recentMap.get(id)||0)-(prevMap.get(id)||0)})).filter(x=>x.post&&x.growth>0).sort((a,b)=>b.growth-a.growth).slice(0,20);const lowTraffic=rows.filter(x=>x.views<=5).sort((a,b)=>a.views-b.views).slice(0,20);const topAffiliate=affiliate.map(x=>({post:map.get(x.entityId),clicks:x._sum.affiliateClicks||0})).filter(x=>x.post).sort((a,b)=>b.clicks-a.clicks).slice(0,20);const categories=new Map<string,number>();for(const row of rows){const n=row.post?.category?.name||"Uncategorized";categories.set(n,(categories.get(n)||0)+row.views)}return{rows:rows.slice(0,100),growing,lowTraffic,topAffiliate,categories:[...categories].sort((a,b)=>b[1]-a[1]).map(([category,views])=>({category,views}))};}
};
