"use client";
import { useEffect,useRef,useState } from "react";
import { Upload,ImageIcon,RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";

type M={id:string;path:string;title:string|null;altText:string|null;variants:{kind:string;path:string}[]};
export function MediaPicker({value,onChange}:{value?:M|null;onChange:(m:M|null)=>void}){
 const [open,setOpen]=useState(false),[items,setItems]=useState<M[]>([]),[loading,setLoading]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState("");
 const fileRef=useRef<HTMLInputElement>(null);
 async function load(){setLoading(true);setError("");try{const r=await fetch('/api/admin/media?page=1&limit=60',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||"Could not load media library.");setItems(j?.data?.items||[])}catch(e){setItems([]);setError(e instanceof Error?e.message:"Could not load media library.")}finally{setLoading(false)}}
 useEffect(()=>{if(open)void load()},[open]);
 async function upload(files:FileList|null){const file=files?.[0];if(!file)return;setUploading(true);setError("");try{const form=new FormData();form.append("file",file);const r=await fetch("/api/admin/media",{method:"POST",body:form});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||"Upload failed.");const uploaded=j?.data as M;if(uploaded?.id){onChange(uploaded);setOpen(false)}else await load()}catch(e){setError(e instanceof Error?e.message:"Upload failed.")}finally{setUploading(false);if(fileRef.current)fileRef.current.value=""}}
 return <div className="space-y-2">{value?<div className="rounded-xl border p-2"><img src={value.variants?.find(v=>v.kind==='card')?.path||value.path} alt={value.altText||''} className="aspect-video w-full rounded-lg object-cover"/><div className="mt-2 flex gap-2"><Button type="button" variant="secondary" onClick={()=>setOpen(true)}>Change</Button><Button type="button" variant="secondary" onClick={()=>onChange(null)}>Remove</Button></div></div>:<Button type="button" variant="secondary" onClick={()=>setOpen(true)}>Choose from Media Library</Button>}{open&&<div className="fixed inset-0 z-[90] grid place-items-center bg-black/40 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="max-h-[85vh] w-full max-w-5xl overflow-auto rounded-2xl bg-white p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold">Choose image</h3><p className="text-xs text-slate-500">Upload a new image or select one from the Media Library.</p></div><div className="flex gap-2"><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="hidden" onChange={e=>void upload(e.target.files)}/><Button type="button" disabled={uploading} onClick={()=>fileRef.current?.click()}><Upload size={16}/>{uploading?"Uploading...":"Upload image"}</Button><Button type="button" variant="secondary" disabled={loading} onClick={()=>void load()}><RefreshCw size={16}/>Refresh</Button><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Close</Button></div></div>{error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{loading?<div className="grid min-h-52 place-items-center text-sm text-slate-500">Loading media library...</div>:items.length?<div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-5">{items.map(m=><button key={m.id} type="button" onClick={()=>{onChange(m);setOpen(false)}} className="overflow-hidden rounded-xl border text-left transition hover:border-blue-400 hover:shadow-sm"><div className="grid aspect-[4/3] place-items-center bg-slate-50"><img src={m.variants?.find(v=>v.kind==='thumb')?.path||m.path} alt={m.altText||''} className="h-full w-full object-cover" onError={e=>{e.currentTarget.style.display='none'}}/></div><p className="truncate p-2 text-sm">{m.title||'Untitled'}</p></button>)}</div>:<div className="grid min-h-52 place-items-center rounded-xl border border-dashed text-center text-sm text-slate-500"><div><ImageIcon className="mx-auto mb-2"/><p>No usable images found.</p><p>Use “Upload image” to add one.</p></div></div>}</div></div>}</div>
}
