import crypto,{createCipheriv,createDecipheriv,randomBytes,createHash} from "node:crypto";
import {prisma} from "@/lib/db/prisma";
import {env} from "@/lib/env";
export const WEBHOOK_EVENTS=["post.published","post.updated","subscriber.created"] as const;
export type WebhookEvent=typeof WEBHOOK_EVENTS[number];
const key=()=>createHash("sha256").update(`${env.SESSION_SECRET}:webhooks`).digest();
function encrypt(v:string){const iv=randomBytes(12),c=createCipheriv("aes-256-gcm",key(),iv);const enc=Buffer.concat([c.update(v,"utf8"),c.final()]);return [iv,c.getAuthTag(),enc].map(x=>x.toString("base64url")).join(".")}
function decrypt(v:string){const [iv,tag,data]=v.split(".").map(x=>Buffer.from(x,"base64url"));const d=createDecipheriv("aes-256-gcm",key(),iv);d.setAuthTag(tag);return Buffer.concat([d.update(data),d.final()]).toString("utf8")}
const safeUrl=(raw:string)=>{const u=new URL(raw);if(!["https:","http:"].includes(u.protocol))throw new Error("Webhook URL must use HTTP or HTTPS.");if(env.NODE_ENV==="production"&&u.protocol!=="https:")throw new Error("Production webhook URLs must use HTTPS.");return u.toString()};
export async function createWebhook(input:{name:string;url:string;secret:string;events:string[]}){const url=safeUrl(input.url);const events=input.events.filter(x=>WEBHOOK_EVENTS.includes(x as WebhookEvent));if(!events.length)throw new Error("Select at least one webhook event.");if(input.secret.length<24)throw new Error("Webhook secret must be at least 24 characters.");return prisma.webhookEndpoint.create({data:{name:input.name.slice(0,120),url,secret:encrypt(input.secret),events}})}
export async function emitWebhook(event:WebhookEvent,payload:Record<string,unknown>){const endpoints=await prisma.webhookEndpoint.findMany({where:{active:true}});const eventId=crypto.randomUUID();let queued=0;for(const endpoint of endpoints){const events=Array.isArray(endpoint.events)?endpoint.events as string[]:[];if(!events.includes(event))continue;const delivery=await prisma.webhookDelivery.create({data:{endpointId:endpoint.id,event,eventId,payload:payload as never}});await prisma.backgroundJob.create({data:{type:"WEBHOOK_DELIVERY",payload:{deliveryId:delivery.id} as never,dedupeKey:`webhook:${delivery.id}`,priority:40,maxAttempts:5,runAt:new Date()}});queued++;}return {eventId,queued}}
export async function deliverWebhook(deliveryId:string){const row=await prisma.webhookDelivery.findUnique({where:{id:deliveryId},include:{endpoint:true}});if(!row||row.succeeded)return {skipped:true};const body=JSON.stringify({id:row.eventId,event:row.event,createdAt:row.createdAt.toISOString(),data:row.payload});const ts=Math.floor(Date.now()/1000).toString();const sig=crypto.createHmac("sha256",decrypt(row.endpoint.secret)).update(`${ts}.${body}`).digest("hex");let status:number|undefined;try{const res=await fetch(safeUrl(row.endpoint.url),{method:"POST",headers:{"content-type":"application/json","user-agent":"PushStream-Webhook/1.0","x-pushstream-event":row.event,"x-pushstream-delivery":row.eventId,"x-pushstream-timestamp":ts,"x-pushstream-signature":`sha256=${sig}`},body,signal:AbortSignal.timeout(10000)});status=res.status;if(!res.ok)throw new Error(`Webhook returned HTTP ${res.status}`);await prisma.webhookDelivery.update({where:{id:row.id},data:{succeeded:true,attempts:{increment:1},statusCode:res.status,deliveredAt:new Date(),lastError:null}});return {succeeded:true,status:res.status};}catch(e){await prisma.webhookDelivery.update({where:{id:row.id},data:{attempts:{increment:1},statusCode:status,lastError:String(e instanceof Error?e.message:e).slice(0,1000)}});throw e}}
