import Link from "next/link";
import { prisma } from "@/lib/db/prisma";
import { requirePermission } from "@/lib/auth/session";
import { hasPermission } from "@/lib/auth/permissions";
import { postService } from "@/services/cms/post.service";
import { AdminPageHeader as PageHeader } from "@/components/admin/shared/page-header";
import { PostBulkTable } from "@/components/admin/cms/post-bulk-table";
import { Button } from "@/components/ui/button";
export default async function PostsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const session=await requirePermission("posts.view");const p=await searchParams;const q=typeof p.q==="string"?p.q:undefined;const status=typeof p.status==="string"?p.status:undefined;const page=Number(typeof p.page==="string"?p.page:1);const result=await postService.list({q,status,page,limit:20,session});const [categories,authors,tags]=await Promise.all([prisma.category.findMany({where:{archivedAt:null},select:{id:true,name:true}}),prisma.user.findMany({where:{status:"ACTIVE",deletedAt:null},select:{id:true,name:true},orderBy:{name:"asc"}}),prisma.tag.findMany({select:{id:true,name:true},orderBy:{name:"asc"}})]);const canCreate=hasPermission(session.user.permissions,"posts.create");const canPublish=hasPermission(session.user.permissions,"posts.publish");return <div className="space-y-6"><PageHeader title="Posts" description="Create, review, schedule, publish and manage editorial content." actions={canCreate?<Link href="/admin/posts/new"><Button>New post</Button></Link>:undefined}/><form className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_220px_auto]"><input name="q" defaultValue={q} placeholder="Search title, slug or excerpt" className="min-h-12 rounded-xl border px-3"/><select name="status" defaultValue={status??""} className="min-h-12 rounded-xl border px-3"><option value="">All statuses</option>{["DRAFT","REVIEW","IN_REVIEW","CHANGES_REQUESTED","APPROVED","SCHEDULED","PUBLISHED","ARCHIVED","TRASH"].map(x=><option key={x}>{x}</option>)}</select><Button type="submit">Filter</Button></form><PostBulkTable rows={result.items.map(post=>({id:post.id,title:post.title,slug:post.slug,status:post.status,views:post.views.toString(),updatedAt:post.updatedAt.toISOString(),author:{name:post.author.name},category:post.category?{name:post.category.name}:null}))} authors={authors} categories={categories} tags={tags} canPublish={canPublish}/><div className="flex items-center justify-between text-sm"><span>Page {result.page} of {result.pages} · {result.total} posts</span><div className="flex gap-2">{result.page>1&&<Link href={`?page=${result.page-1}${q?`&q=${encodeURIComponent(q)}`:""}`}><Button variant="secondary">Previous</Button></Link>}{result.page<result.pages&&<Link href={`?page=${result.page+1}${q?`&q=${encodeURIComponent(q)}`:""}`}><Button variant="secondary">Next</Button></Link>}</div></div></div>}
