import { prisma } from "@/lib/db/prisma";
export type SearchType="all"|"posts"|"pages"|"tools"|"reviews"|"categories";
export type SearchSort="relevance"|"latest"|"oldest";
export type SearchItem={kind:string;title:string;url:string;excerpt:string|null;date:Date|null;score:number};
function sinceFor(date?:string){const d=new Date();if(date==="day")d.setDate(d.getDate()-1);else if(date==="week")d.setDate(d.getDate()-7);else if(date==="month")d.setMonth(d.getMonth()-1);else if(date==="year")d.setFullYear(d.getFullYear()-1);else return undefined;return d}
function rank(title:string,excerpt:string|null,term:string,bonus=0){const q=term.toLowerCase(),t=title.toLowerCase(),e=(excerpt||"").toLowerCase();let n=bonus;if(t===q)n+=120;else if(t.startsWith(q))n+=90;else if(t.includes(q))n+=65;if(e.includes(q))n+=20;for(const token of q.split(/\s+/).filter(x=>x.length>1)){if(t.includes(token))n+=12;if(e.includes(token))n+=3}return n}
export async function searchSite({q,type="all",page=1,limit=10,category,date,sort="relevance"}:{q:string;type?:SearchType;page?:number;limit?:number;category?:string;date?:string;sort?:SearchSort}){const term=q.trim();if(!term)return {items:[],total:0,pages:1,logId:null};const since=sinceFor(date);const categoryRow=category?await prisma.category.findUnique({where:{slug:category},select:{id:true}}):null;const take=type==="all"?80:Math.min(120,page*limit+40);const postWhere={status:"PUBLISHED" as const,deletedAt:null,publishedAt:{lte:new Date(),...(since?{gte:since}:{})},...(categoryRow?{categoryId:categoryRow.id}:{}),OR:[{title:{contains:term}},{subtitle:{contains:term}},{excerpt:{contains:term}},{focusKeyword:{contains:term}},{category:{name:{contains:term}}},{tags:{some:{tag:{name:{contains:term}}}}}]};
const [posts,pages,tools,reviews,categories]=await Promise.all([
(type==="all"||type==="posts")?prisma.post.findMany({where:postWhere,take,orderBy:{publishedAt:"desc"},select:{title:true,slug:true,excerpt:true,publishedAt:true,category:{select:{name:true}},tags:{select:{tag:{select:{name:true}}}}}}):[],
(type==="all"||type==="pages")?prisma.page.findMany({where:{status:"PUBLISHED",deletedAt:null,publishedAt:{lte:new Date(),...(since?{gte:since}:{})},OR:[{title:{contains:term}},{seoDescription:{contains:term}}]},take,select:{title:true,slug:true,seoDescription:true,publishedAt:true}}):[],
(type==="all"||type==="tools")?prisma.aiTool.findMany({where:{status:"PUBLISHED",deletedAt:null,...(since?{updatedAt:{gte:since}}:{}),OR:[{name:{contains:term}},{shortDescription:{contains:term}},{features:{some:{name:{contains:term}}}},{useCases:{some:{name:{contains:term}}}}]},take,select:{name:true,slug:true,shortDescription:true,updatedAt:true}}):[],
(type==="all"||type==="reviews")?prisma.review.findMany({where:{status:"PUBLISHED",deletedAt:null,publishedAt:{lte:new Date(),...(since?{gte:since}:{})},OR:[{title:{contains:term}},{bestFor:{contains:term}},{verdict:{contains:term}}]},take,select:{title:true,slug:true,bestFor:true,publishedAt:true}}):[],
(type==="all"||type==="categories")?prisma.category.findMany({where:{archivedAt:null,OR:[{name:{contains:term}},{description:{contains:term}}]},take,select:{name:true,slug:true,description:true,updatedAt:true}}):[]]);
let items:SearchItem[]=[
...posts.map(x=>({kind:"Article",title:x.title,url:`/article/${x.slug}`,excerpt:x.excerpt,date:x.publishedAt,score:rank(x.title,x.excerpt,term,(x.category?.name||"").toLowerCase().includes(term.toLowerCase())?15:0)+x.tags.filter(t=>t.tag.name.toLowerCase().includes(term.toLowerCase())).length*10})),
...pages.map(x=>({kind:"Page",title:x.title,url:`/${x.slug}`,excerpt:x.seoDescription,date:x.publishedAt,score:rank(x.title,x.seoDescription,term)})),
...tools.map(x=>({kind:"AI Tool",title:x.name,url:`/ai-tools/${x.slug}`,excerpt:x.shortDescription,date:x.updatedAt,score:rank(x.name,x.shortDescription,term,8)})),
...reviews.map(x=>({kind:"Review",title:x.title,url:`/reviews/${x.slug}`,excerpt:x.bestFor,date:x.publishedAt,score:rank(x.title,x.bestFor,term,5)})),
...categories.map(x=>({kind:"Category",title:x.name,url:`/category/${x.slug}`,excerpt:x.description,date:x.updatedAt,score:rank(x.name,x.description,term,10)}))];
if(sort==="relevance")items.sort((a,b)=>b.score-a.score||((b.date?.getTime()||0)-(a.date?.getTime()||0)));else items.sort((a,b)=>sort==="oldest"?(a.date?.getTime()||0)-(b.date?.getTime()||0):(b.date?.getTime()||0)-(a.date?.getTime()||0));const total=items.length;const start=(page-1)*limit;items=items.slice(start,start+limit);const log=await prisma.searchLog.create({data:{term,normalizedTerm:term.toLowerCase(),resultCount:total,contentType:type}}).catch(()=>null);return {items,total,pages:Math.max(1,Math.ceil(total/limit)),logId:log?.id??null}}
export async function searchSuggestions(q:string){const term=q.trim();if(term.length<2)return [];const [posts,tools,categories]=await Promise.all([prisma.post.findMany({where:{status:"PUBLISHED",deletedAt:null,publishedAt:{lte:new Date()},title:{contains:term}},orderBy:[{views:"desc"},{publishedAt:"desc"}],take:5,select:{title:true,slug:true}}),prisma.aiTool.findMany({where:{status:"PUBLISHED",deletedAt:null,name:{contains:term}},orderBy:{views:"desc"},take:4,select:{name:true,slug:true}}),prisma.category.findMany({where:{archivedAt:null,name:{contains:term}},take:4,select:{name:true,slug:true}})]);return [...posts.map(x=>({type:"Article",title:x.title,url:`/article/${x.slug}`})),...tools.map(x=>({type:"AI Tool",title:x.name,url:`/ai-tools/${x.slug}`})),...categories.map(x=>({type:"Category",title:x.name,url:`/category/${x.slug}`}))].slice(0,10)}
