-- Phase 17: editorial workflow, collaboration, editor locks, preview tokens and author expertise
ALTER TABLE `Post` MODIFY `status` ENUM('DRAFT','REVIEW','IN_REVIEW','CHANGES_REQUESTED','APPROVED','SCHEDULED','PUBLISHED','ARCHIVED','TRASH') NOT NULL DEFAULT 'DRAFT';
ALTER TABLE `Notification` MODIFY `type` ENUM('CONTACT_MESSAGE','COMMENT_PENDING','SCHEDULED_POST_FAILED','SYSTEM','SUBSCRIBER_MILESTONE','EDITORIAL_SUBMITTED','EDITORIAL_CHANGES_REQUESTED','EDITORIAL_APPROVED','EDITORIAL_SCHEDULED','EDITORIAL_PUBLISHED') NOT NULL;
ALTER TABLE `Post` ADD COLUMN `reviewDueAt` DATETIME(3) NULL, ADD COLUMN `lastMeaningfulUpdateAt` DATETIME(3) NULL;
ALTER TABLE `AuthorProfile` ADD COLUMN `github` VARCHAR(191) NULL;
CREATE TABLE `AuthorExpertise` (`id` VARCHAR(191) NOT NULL,`authorProfileId` VARCHAR(191) NOT NULL,`topic` VARCHAR(191) NOT NULL,`sortOrder` INTEGER NOT NULL DEFAULT 0,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY (`id`),UNIQUE INDEX `AuthorExpertise_authorProfileId_topic_key`(`authorProfileId`,`topic`),INDEX `AuthorExpertise_authorProfileId_sortOrder_idx`(`authorProfileId`,`sortOrder`),CONSTRAINT `AuthorExpertise_authorProfileId_fkey` FOREIGN KEY (`authorProfileId`) REFERENCES `AuthorProfile`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `EditorialReview` (`id` VARCHAR(191) NOT NULL,`postId` VARCHAR(191) NOT NULL,`reviewerId` VARCHAR(191) NULL,`submittedAt` DATETIME(3) NULL,`reviewedAt` DATETIME(3) NULL,`approvedAt` DATETIME(3) NULL,`changesRequestedAt` DATETIME(3) NULL,`reviewNotes` TEXT NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),`updatedAt` DATETIME(3) NOT NULL,PRIMARY KEY (`id`),UNIQUE INDEX `EditorialReview_postId_key`(`postId`),INDEX `EditorialReview_reviewerId_reviewedAt_idx`(`reviewerId`,`reviewedAt`),INDEX `EditorialReview_submittedAt_idx`(`submittedAt`),CONSTRAINT `EditorialReview_postId_fkey` FOREIGN KEY (`postId`) REFERENCES `Post`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `EditorialReview_reviewerId_fkey` FOREIGN KEY (`reviewerId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `EditorialNote` (`id` VARCHAR(191) NOT NULL,`postId` VARCHAR(191) NOT NULL,`userId` VARCHAR(191) NOT NULL,`note` TEXT NOT NULL,`resolvedAt` DATETIME(3) NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),`updatedAt` DATETIME(3) NOT NULL,PRIMARY KEY (`id`),INDEX `EditorialNote_postId_resolvedAt_createdAt_idx`(`postId`,`resolvedAt`,`createdAt`),INDEX `EditorialNote_userId_createdAt_idx`(`userId`,`createdAt`),CONSTRAINT `EditorialNote_postId_fkey` FOREIGN KEY (`postId`) REFERENCES `Post`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `EditorialNote_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `PostEditorLock` (`id` VARCHAR(191) NOT NULL,`postId` VARCHAR(191) NOT NULL,`userId` VARCHAR(191) NOT NULL,`acquiredAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),`heartbeatAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),`expiresAt` DATETIME(3) NOT NULL,PRIMARY KEY (`id`),UNIQUE INDEX `PostEditorLock_postId_key`(`postId`),INDEX `PostEditorLock_expiresAt_idx`(`expiresAt`),INDEX `PostEditorLock_userId_expiresAt_idx`(`userId`,`expiresAt`),CONSTRAINT `PostEditorLock_postId_fkey` FOREIGN KEY (`postId`) REFERENCES `Post`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `PostEditorLock_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `PreviewToken` (`id` VARCHAR(191) NOT NULL,`postId` VARCHAR(191) NOT NULL,`createdById` VARCHAR(191) NOT NULL,`tokenHash` VARCHAR(191) NOT NULL,`expiresAt` DATETIME(3) NOT NULL,`revokedAt` DATETIME(3) NULL,`createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY (`id`),UNIQUE INDEX `PreviewToken_tokenHash_key`(`tokenHash`),INDEX `PreviewToken_postId_expiresAt_idx`(`postId`,`expiresAt`),INDEX `PreviewToken_createdById_createdAt_idx`(`createdById`,`createdAt`),CONSTRAINT `PreviewToken_postId_fkey` FOREIGN KEY (`postId`) REFERENCES `Post`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `PreviewToken_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE INDEX `Post_reviewDueAt_status_idx` ON `Post`(`reviewDueAt`,`status`);
