import Link from "next/link";
import { requirePermission } from "@/lib/auth/session";
import { AdminPageHeader } from "@/components/admin/shared/page-header";
import { seoAdminService } from "@/services/seo/seo.service";
import { redirectService } from "@/services/seo/redirect.service";
import { deleteRedirect, saveRedirect, saveSeoSettings } from "./actions";
import { RedirectImport } from "@/components/admin/seo/redirect-import";

const str=(v:unknown)=>typeof v==="string"?v:"";
const bool=(v:unknown,f=true)=>typeof v==="boolean"?v:f;
export default async function SeoPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  await requirePermission("seo.view"); const s=await searchParams; const page=Math.max(1,Number(s.page||1));
  const [settings,redirects]=await Promise.all([seoAdminService.settings(),redirectService.list(s.q||"",page)]);
  return <div className="space-y-8"><AdminPageHeader title="SEO & Redirects" description="Control site-wide metadata defaults, crawl directives, feeds and URL redirects." actions={<div className="flex flex-wrap gap-2"><Link className="rounded-xl border px-4 py-3 text-sm font-bold" href="/admin/seo/content">Content SEO</Link><Link className="rounded-xl border px-4 py-3 text-sm font-bold" href="/admin/seo/orphan-content">Orphans</Link><Link className="rounded-xl border px-4 py-3 text-sm font-bold" href="/admin/seo/broken-links">Broken links</Link><Link className="rounded-xl border px-4 py-3 text-sm font-bold" href="/admin/seo/404s">404s</Link><a className="rounded-xl border px-4 py-3 text-sm font-bold" href="/sitemap.xml" target="_blank">Sitemap</a><a className="rounded-xl border px-4 py-3 text-sm font-bold" href="/rss.xml" target="_blank">RSS</a></div>}/>
  <form action={saveSeoSettings} className="space-y-5 rounded-2xl border bg-white p-5"><div><h2 className="text-xl font-extrabold">Global SEO defaults</h2><p className="text-sm text-[var(--text-muted)]">Entity-level metadata overrides these defaults.</p></div><div className="grid gap-4 md:grid-cols-2"><Field label="Default title"><input name="defaultTitle" defaultValue={str(settings["seo.defaultTitle"])||"PushStream"} className="min-h-12 w-full rounded-xl border px-3"/></Field><Field label="Twitter card"><select name="twitterCard" defaultValue={str(settings["seo.twitterCard"])||"summary_large_image"} className="min-h-12 w-full rounded-xl border px-3"><option value="summary_large_image">Large image</option><option value="summary">Summary</option></select></Field></div><Field label="Default meta description"><textarea name="metaDescription" defaultValue={str(settings["seo.metaDescription"])} rows={3} className="w-full rounded-xl border p-3"/></Field><Field label="Default Open Graph image URL"><input name="ogImage" defaultValue={str(settings["seo.ogImage"])} placeholder="/uploads/... or https://..." className="min-h-12 w-full rounded-xl border px-3"/></Field><div className="flex flex-wrap gap-6"><Check name="robotsIndex" label="Allow indexing" defaultChecked={bool(settings["seo.robotsIndex"])}/><Check name="robotsFollow" label="Allow link following" defaultChecked={bool(settings["seo.robotsFollow"])}/></div><button className="rounded-xl bg-[var(--primary)] px-5 py-3 font-bold text-white">Save SEO settings</button></form>
  <section className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-extrabold">Redirect manager</h2><p className="text-sm text-[var(--text-muted)]">Use permanent redirects for moved URLs and temporary redirects only when the change is not permanent.</p></div><a href="/api/admin/seo/redirects/export" className="rounded-xl border px-4 py-3 text-sm font-bold">Export CSV</a></div><RedirectImport/><form action={saveRedirect} className="grid gap-3 rounded-2xl border bg-white p-4 lg:grid-cols-[1fr_1fr_160px_auto_auto]"><input name="oldPath" required placeholder="/old-path" className="min-h-12 rounded-xl border px-3"/><input name="newPath" required placeholder="/new-path or https://..." className="min-h-12 rounded-xl border px-3"/><select name="type" className="min-h-12 rounded-xl border px-3"><option value="PERMANENT">Permanent</option><option value="TEMPORARY">Temporary</option></select><label className="flex items-center gap-2 px-2 text-sm font-semibold"><input type="checkbox" name="active" defaultChecked/>Active</label><button className="rounded-xl bg-[var(--foreground)] px-4 font-bold text-white">Add redirect</button></form><form className="flex gap-2"><input name="q" defaultValue={s.q} placeholder="Search redirects…" className="min-h-11 min-w-0 flex-1 rounded-xl border px-3"/><button className="rounded-xl border px-4 font-bold">Search</button></form><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[var(--background-soft)] text-left"><tr><th className="p-4">Old path</th><th>Destination</th><th>Type</th><th>Hits</th><th>Last hit</th><th>Status</th><th className="p-4">Actions</th></tr></thead><tbody>{redirects.items.map(r=><tr key={r.id} className="border-t"><td className="p-4 font-mono">{r.oldPath}</td><td className="max-w-xs truncate">{r.newPath}</td><td>{r.type}</td><td>{r.hits.toString()}</td><td>{r.lastHitAt?.toLocaleString()||"—"}</td><td>{r.active?"Active":"Disabled"}</td><td className="p-4"><form action={deleteRedirect}><input type="hidden" name="id" value={r.id}/><button className="rounded-lg border px-3 py-2 text-red-700">Delete</button></form></td></tr>)}{redirects.items.length===0&&<tr><td colSpan={7} className="p-8 text-center text-[var(--text-muted)]">No redirects found.</td></tr>}</tbody></table></div><div className="flex items-center justify-between"><span className="text-sm text-[var(--text-muted)]">{redirects.total} redirects</span><div className="flex gap-2">{page>1&&<Link className="rounded-lg border px-3 py-2" href={{pathname:"/admin/seo",query:{...s,page:page-1}}}>Previous</Link>}{page<redirects.pages&&<Link className="rounded-lg border px-3 py-2" href={{pathname:"/admin/seo",query:{...s,page:page+1}}}>Next</Link>}</div></div></section></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-medium">{label}<div className="mt-2">{children}</div></label>}
function Check({name,label,defaultChecked}:{name:string;label:string;defaultChecked:boolean}){return <label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name={name} defaultChecked={defaultChecked}/>{label}</label>}
