import { prisma } from "@/lib/db/prisma";

export function normalizeAffiliateSlug(value:string){const s=value.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(!s)throw new Error("A valid slug is required.");return s}
export function assertHttpUrl(value:string){const u=new URL(value);if(!["http:","https:"].includes(u.protocol))throw new Error("Only http/https destinations are allowed.");return u.toString()}
export function sourceFromReferrer(referrer:string|null,siteUrl=process.env.SITE_URL||"https://pushstream.online"){if(!referrer)return {sourcePage:null as string|null,sourcePostSlug:null as string|null};try{const u=new URL(referrer),site=new URL(siteUrl);const internal=u.origin===site.origin||u.hostname==="pushstream.online";const path=u.pathname.slice(0,500)||"/";const m=internal?path.match(/^\/article\/([^/?#]+)/):null;return{sourcePage:internal?path:`external:${u.hostname}`.slice(0,500),sourcePostSlug:m?.[1]||null}}catch{return{sourcePage:null,sourcePostSlug:null}}}
export const affiliateService={
 async list(q="",page=1){const take=25,skip=(page-1)*take,where=q?{OR:[{name:{contains:q}},{slug:{contains:q}},{campaign:{contains:q}}]}:{};const [items,total]=await prisma.$transaction([prisma.affiliateLink.findMany({where,orderBy:{createdAt:"desc"},skip,take}),prisma.affiliateLink.count({where})]);return{items,total,pages:Math.max(1,Math.ceil(total/take))}},
 async resolve(slug:string,referrer:string|null,track=true){const link=await prisma.affiliateLink.findUnique({where:{slug}});if(!link?.active)return null;if(track){const source=sourceFromReferrer(referrer);const post=source.sourcePostSlug?await prisma.post.findFirst({where:{slug:source.sourcePostSlug},select:{id:true}}):null;await prisma.$transaction([prisma.affiliateClick.create({data:{affiliateLinkId:link.id,referrer:referrer?.slice(0,2000)||null,sourcePage:source.sourcePage,sourcePostId:post?.id||null}}),prisma.affiliateLink.update({where:{id:link.id},data:{clicks:{increment:1}}})])}return link.affiliateUrl||link.destinationUrl},
 async top(days=30){const from=new Date(Date.now()-days*86400000);const grouped=await prisma.affiliateClick.groupBy({by:["affiliateLinkId"],where:{createdAt:{gte:from}},_count:{_all:true}});const links=await prisma.affiliateLink.findMany({where:{id:{in:grouped.map(x=>x.affiliateLinkId)}}});const map=new Map(links.map(x=>[x.id,x]));return grouped.map(x=>({link:map.get(x.affiliateLinkId),clicks:x._count._all})).filter(x=>x.link).sort((a,b)=>b.clicks-a.clicks)},
 async analytics(){const now=Date.now(),d1=new Date(now-86400000),d7=new Date(now-7*86400000),d30=new Date(now-30*86400000);const [today,week,month,topLinks,topSources,topPosts]=await Promise.all([
  prisma.affiliateClick.count({where:{createdAt:{gte:d1}}}),
  prisma.affiliateClick.count({where:{createdAt:{gte:d7}}}),
  prisma.affiliateClick.count({where:{createdAt:{gte:d30}}}),
  prisma.affiliateClick.groupBy({by:["affiliateLinkId"],where:{createdAt:{gte:d30}},_count:{_all:true},orderBy:{_count:{affiliateLinkId:"desc"}},take:10}),
  prisma.affiliateClick.groupBy({by:["sourcePage"],where:{createdAt:{gte:d30},sourcePage:{not:null}},_count:{_all:true},orderBy:{_count:{sourcePage:"desc"}},take:10}),
  prisma.affiliateClick.groupBy({by:["sourcePostId"],where:{createdAt:{gte:d30},sourcePostId:{not:null}},_count:{_all:true},orderBy:{_count:{sourcePostId:"desc"}},take:10})
 ]);const linkRows=await prisma.affiliateLink.findMany({where:{id:{in:topLinks.map(x=>x.affiliateLinkId)}},select:{id:true,name:true,slug:true}});const postRows=await prisma.post.findMany({where:{id:{in:topPosts.flatMap(x=>x.sourcePostId?[x.sourcePostId]:[])}},select:{id:true,title:true,slug:true}});const lm=new Map(linkRows.map(x=>[x.id,x])),pm=new Map(postRows.map(x=>[x.id,x]));return{today,week,month,topLinks:topLinks.map(x=>({link:lm.get(x.affiliateLinkId),clicks:x._count._all})).filter(x=>x.link),topSources:topSources.map(x=>({sourcePage:x.sourcePage,clicks:x._count._all})),topPosts:topPosts.map(x=>({post:x.sourcePostId?pm.get(x.sourcePostId):null,clicks:x._count._all})).filter(x=>x.post)}}
};
