import { Bot, CheckCircle2, CircleOff, ShieldAlert } from "lucide-react";
import { requirePermission } from "@/lib/auth/session";
import { hasPermission } from "@/lib/auth/permissions";
import { aiService, getAiConfig } from "@/services/ai/ai.service";
import { AdminPageHeader } from "@/components/admin/shared/page-header";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { saveAiSettings } from "./actions";

const modelExamples={OPENAI:"gpt-5.6-luna",ANTHROPIC:"claude-sonnet-5",GEMINI:"gemini-3.8-flash",LOCAL:"your-local-model"} as const;
export default async function AiWorkspacePage(){
 const session=await requirePermission("ai.view");const [cfg,usage,history]=await Promise.all([getAiConfig(),aiService.usage(session),aiService.history(session,30)]);const canManage=hasPermission(session.user.permissions,"ai.manage");
 return <div className="space-y-6"><AdminPageHeader eyebrow="Editorial AI" title="AI-Assisted Content Workspace" description="Optional drafting assistance with mandatory human editorial review. AI output is never published automatically."/>
 <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><div className="flex gap-2"><ShieldAlert className="h-5 w-5 shrink-0"/><div><strong>Editorial safeguard:</strong> AI-generated content should be reviewed before publishing. Ratings, reviews, sources, statistics, testimonials, quotes and product claims remain editor-controlled.</div></div></div>
 <div className="grid gap-5 md:grid-cols-3"><Card><p className="text-sm text-[var(--text-muted)]">Your requests today</p><p className="mt-2 text-3xl font-bold">{usage.userRequests} / {cfg.perUserDailyLimit}</p></Card><Card><p className="text-sm text-[var(--text-muted)]">Site requests today</p><p className="mt-2 text-3xl font-bold">{usage.globalRequests} / {cfg.dailyLimit}</p></Card><Card><p className="text-sm text-[var(--text-muted)]">Current provider</p><p className="mt-2 flex items-center gap-2 text-xl font-bold"><Bot className="h-5 w-5"/>{cfg.provider}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{cfg.model}</p></Card></div>
 <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_420px]"><Card><h2 className="text-lg font-bold">Activity history</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Prompt bodies and API credentials are not stored here.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">When</th><th className="p-3">Editor</th><th className="p-3">Action</th><th className="p-3">Provider / model</th><th className="p-3">Post</th><th className="p-3">Accepted</th></tr></thead><tbody>{history.map(row=><tr key={row.id} className="border-b last:border-0"><td className="p-3">{row.createdAt.toLocaleString()}</td><td className="p-3">{row.user.name}</td><td className="p-3 font-medium">{row.actionType}</td><td className="p-3">{row.provider}<div className="text-xs text-[var(--text-muted)]">{row.model}</div></td><td className="p-3">{row.post?.title||"—"}</td><td className="p-3">{row.acceptedAt?<CheckCircle2 className="h-4 w-4 text-green-700"/>:<CircleOff className="h-4 w-4 text-slate-400"/>}</td></tr>)}{history.length===0&&<tr><td colSpan={6} className="p-8 text-center text-[var(--text-muted)]">No AI activity yet.</td></tr>}</tbody></table></div></Card>
 <Card><h2 className="text-lg font-bold">Provider & limits</h2><p className="mt-1 text-xs text-[var(--text-muted)]">API credentials are read only from server environment variables and are never returned to this page.</p>{canManage?<form action={saveAiSettings} className="mt-5 space-y-4"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="enabled" defaultChecked={cfg.enabled}/> Enable AI assistance</label><label className="block text-sm font-semibold">Provider<select name="provider" defaultValue={cfg.provider} className="mt-2 min-h-12 w-full rounded-xl border px-3">{(["OPENAI","ANTHROPIC","GEMINI","LOCAL"] as const).map(p=><option key={p} value={p}>{p} · {cfg.providerConfigured[p]?"configured":"key/endpoint missing"}</option>)}</select></label><label className="block text-sm font-semibold">Model<Input name="model" defaultValue={cfg.model} placeholder={modelExamples[cfg.provider as keyof typeof modelExamples]} className="mt-2"/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Max output tokens<Input name="maxTokens" type="number" min="128" max="16000" defaultValue={cfg.maxTokens} className="mt-2"/></label><label className="text-sm font-semibold">Site daily calls<Input name="dailyLimit" type="number" min="1" defaultValue={cfg.dailyLimit} className="mt-2"/></label></div><label className="block text-sm font-semibold">Per-user daily calls<Input name="perUserDailyLimit" type="number" min="1" defaultValue={cfg.perUserDailyLimit} className="mt-2"/></label><fieldset className="space-y-2 rounded-xl border p-3"><legend className="px-1 text-sm font-semibold">Features</legend>{[["featureRewrite","Rewrite / summary",cfg.features.rewrite],["featureMetadata","Metadata / titles",cfg.features.metadata],["featureOutline","Outline / headings",cfg.features.outline],["featureFaq","FAQ",cfg.features.faq],["featureLinks","Internal-link ideas",cfg.features.links]].map(([name,label,on])=><label key={String(name)} className="flex items-center gap-2 text-sm"><input type="checkbox" name={String(name)} defaultChecked={Boolean(on)}/>{String(label)}</label>)}</fieldset><Button>Save AI settings</Button></form>:<p className="mt-5 text-sm text-[var(--text-muted)]">You can use enabled AI features but do not have permission to change provider settings.</p>}</Card></div></div>
}
