"use server";
import {revalidatePath} from "next/cache";
import {requirePermission} from "@/lib/auth/session";
import {auditService} from "@/services/audit/audit.service";
import {pageSectionsService} from "@/services/site/page-sections.service";
import {getPageDefinition,isPublicPageKey,isPublicSectionType} from "@/lib/site/page-section-registry";

function nullable(fd:FormData,key:string,max=10000){const v=String(fd.get(key)??"").trim();return v?v.slice(0,max):null}
function number(fd:FormData,key:string,fallback:number){const n=Number(fd.get(key));return Number.isFinite(n)?n:fallback}
function revalidate(pageKey:string){const d=getPageDefinition(pageKey);revalidatePath("/admin/site-pages");revalidatePath(`/admin/site-pages/${pageKey}`);if(d)revalidatePath(d.href);}

export async function ensurePageDefaultsAction(fd:FormData){const s=await requirePermission("sitePages.manage");const pageKey=String(fd.get("pageKey")??"");if(!isPublicPageKey(pageKey))throw new Error("Invalid page");await pageSectionsService.ensureDefaults(pageKey);await auditService.record({userId:s.user.id,action:"sitePage.defaults.ensure",entityType:"PublicPageSection",entityId:pageKey});revalidate(pageKey)}

export async function savePageSectionAction(fd:FormData){const s=await requirePermission("sitePages.manage");const pageKey=String(fd.get("pageKey")??"");const sectionKey=String(fd.get("sectionKey")??"");const sectionType=String(fd.get("sectionType")??"");if(!isPublicPageKey(pageKey)||!isPublicSectionType(sectionType)||!/^[a-z0-9-]+$/.test(sectionKey))throw new Error("Invalid section");const manualSelection=String(fd.get("manualSelection")??"").split(",").map(x=>x.trim()).filter(Boolean).slice(0,50);const row=await pageSectionsService.save({pageKey,sectionKey,sectionType,enabled:fd.get("enabled")==="on",heading:nullable(fd,"heading",255),description:nullable(fd,"description"),sortOrder:Math.max(0,number(fd,"sortOrder",10)),dataSource:nullable(fd,"dataSource",80),itemCount:Math.min(50,Math.max(1,number(fd,"itemCount",6))),imageId:nullable(fd,"imageId",191),config:{eyebrow:nullable(fd,"eyebrow",160)??undefined,accentText:nullable(fd,"accentText",255)??undefined,primaryCtaLabel:nullable(fd,"primaryCtaLabel",120)??undefined,primaryCtaUrl:nullable(fd,"primaryCtaUrl",1000)??undefined,secondaryCtaLabel:nullable(fd,"secondaryCtaLabel",120)??undefined,secondaryCtaUrl:nullable(fd,"secondaryCtaUrl",1000)??undefined,stylePreset:String(fd.get("stylePreset")??"white"),manualSelection,visibleFrom:nullable(fd,"visibleFrom",40)??undefined,visibleUntil:nullable(fd,"visibleUntil",40)??undefined,showSidebarTrending:fd.get("showSidebarTrending")==="on",showSidebarCategories:fd.get("showSidebarCategories")==="on",showSidebarNewsletter:fd.get("showSidebarNewsletter")==="on",showSidebarTools:fd.get("showSidebarTools")==="on"}});await auditService.record({userId:s.user.id,action:"sitePage.section.save",entityType:"PublicPageSection",entityId:row.id,metadata:{pageKey,sectionKey,sectionType}});revalidate(pageKey)}

export async function addPageSectionItemAction(fd:FormData){const s=await requirePermission("sitePages.manage");const pageKey=String(fd.get("pageKey")??"");if(!isPublicPageKey(pageKey))throw new Error("Invalid page");const row=await pageSectionsService.addItem({sectionId:String(fd.get("sectionId")??""),itemKey:nullable(fd,"itemKey",100),title:nullable(fd,"title",255),subtitle:nullable(fd,"subtitle",255),body:nullable(fd,"body"),icon:nullable(fd,"icon",80),imageId:nullable(fd,"imageId",191),url:nullable(fd,"url",1000),sortOrder:Math.max(0,number(fd,"sortOrder",10)),enabled:fd.get("enabled")==="on",config:{}});await auditService.record({userId:s.user.id,action:"sitePage.item.create",entityType:"PublicPageSectionItem",entityId:row.id,metadata:{pageKey}});revalidate(pageKey)}

export async function deletePageSectionItemAction(fd:FormData){const s=await requirePermission("sitePages.manage");const pageKey=String(fd.get("pageKey")??""),id=String(fd.get("id")??"");if(!isPublicPageKey(pageKey)||!id)throw new Error("Invalid item");await pageSectionsService.removeItem(id);await auditService.record({userId:s.user.id,action:"sitePage.item.delete",entityType:"PublicPageSectionItem",entityId:id,metadata:{pageKey}});revalidate(pageKey)}

export async function reorderPageSectionsAction(pageKey:string,ids:string[]){const s=await requirePermission("sitePages.manage");await pageSectionsService.reorder(pageKey,ids);await auditService.record({userId:s.user.id,action:"sitePage.sections.reorder",entityType:"PublicPageSection",entityId:pageKey,metadata:{count:ids.length}});revalidate(pageKey)}

export async function updatePageSectionItemAction(fd:FormData){const s=await requirePermission("sitePages.manage");const pageKey=String(fd.get("pageKey")??""),id=String(fd.get("id")??"");if(!isPublicPageKey(pageKey)||!id)throw new Error("Invalid item");const row=await pageSectionsService.updateItem(id,{sectionId:String(fd.get("sectionId")??""),itemKey:nullable(fd,"itemKey",100),title:nullable(fd,"title",255),subtitle:nullable(fd,"subtitle",255),body:nullable(fd,"body"),icon:nullable(fd,"icon",80),imageId:nullable(fd,"imageId",191),url:nullable(fd,"url",1000),sortOrder:Math.max(0,number(fd,"sortOrder",10)),enabled:fd.get("enabled")==="on",config:{}});await auditService.record({userId:s.user.id,action:"sitePage.item.update",entityType:"PublicPageSectionItem",entityId:row.id,metadata:{pageKey}});revalidate(pageKey)}

export async function reorderPageSectionItemsAction(pageKey:string,sectionId:string,ids:string[]){const s=await requirePermission("sitePages.manage");if(!isPublicPageKey(pageKey))throw new Error("Invalid page");await pageSectionsService.reorderItems(sectionId,ids);await auditService.record({userId:s.user.id,action:"sitePage.items.reorder",entityType:"PublicPageSectionItem",entityId:sectionId,metadata:{pageKey,count:ids.length}});revalidate(pageKey)}

export async function duplicatePageSectionAction(pageKey:string,sectionId:string){const s=await requirePermission("sitePages.manage");if(!isPublicPageKey(pageKey))throw new Error("Invalid page");const row=await pageSectionsService.duplicate(pageKey,sectionId);await auditService.record({userId:s.user.id,action:"sitePage.section.duplicate",entityType:"PublicPageSection",entityId:row.id,metadata:{pageKey,sourceSectionId:sectionId}});revalidate(pageKey)}

export async function resetPageSectionAction(pageKey:string,sectionKey:string){const s=await requirePermission("sitePages.manage");if(!isPublicPageKey(pageKey))throw new Error("Invalid page");await pageSectionsService.resetToDefault(pageKey,sectionKey);await auditService.record({userId:s.user.id,action:"sitePage.section.reset",entityType:"PublicPageSection",entityId:sectionKey,metadata:{pageKey}});revalidate(pageKey)}
