import {Prisma} from "@/generated/prisma/client";
import {prisma} from "@/lib/db/prisma";
import {uniqueSlug} from "@/lib/cms/slug";
import {comparisonSchema} from "@/lib/validation/comparisons";
import {auditService} from "@/services/audit/audit.service";
import type {CurrentSession} from "@/lib/auth/session";
async function exists(slug:string,except?:string){return !!await prisma.comparison.findFirst({where:{slug,...(except?{id:{not:except}}:{})},select:{id:true}})}
function featureData(x:any,sortOrder:number,comparisonId:string){return {comparisonId,feature:x.feature,valueType:x.valueType,valueA:x.valueA||null,valueB:x.valueB||null,valueC:x.valueC||null,sortOrder};}
export const comparisonService={
  async list({q="",status="",page=1,limit=20}:{q?:string;status?:string;page?:number;limit?:number}){const where:Prisma.ComparisonWhereInput={deletedAt:null,...(q?{title:{contains:q}}:{}),...(status?{status:status as any}:{})};const [items,total]=await prisma.$transaction([prisma.comparison.findMany({where,include:{items:{orderBy:{sortOrder:"asc"}},_count:{select:{features:true}}},orderBy:{updatedAt:"desc"},skip:(page-1)*limit,take:limit}),prisma.comparison.count({where})]);return{items,total,page,pages:Math.max(1,Math.ceil(total/limit))}},
  get:(id:string)=>prisma.comparison.findFirst({where:{id,deletedAt:null},include:{items:{orderBy:{sortOrder:"asc"}},features:{orderBy:{sortOrder:"asc"}}}}),
  async create(raw:unknown,s:CurrentSession){const v=comparisonSchema.parse(raw),slug=await uniqueSlug(v.slug||v.title,x=>exists(x));const row=await prisma.$transaction(async tx=>{const c=await tx.comparison.create({data:{title:v.title,slug,introduction:v.introduction||null,status:v.status,publishedAt:v.status==="PUBLISHED"?(v.publishedAt?new Date(v.publishedAt):new Date()):v.publishedAt?new Date(v.publishedAt):null}});await tx.comparisonItem.createMany({data:v.items.map((x,sortOrder)=>({comparisonId:c.id,label:x.label,productName:x.productName,productUrl:x.productUrl||null,affiliateUrl:x.affiliateUrl||null,sortOrder}))});await tx.comparisonFeature.createMany({data:v.features.map((x,sortOrder)=>featureData(x,sortOrder,c.id))});return c});await auditService.record({userId:s.user.id,action:"comparison.create",entityType:"Comparison",entityId:row.id});return row},
  async update(id:string,raw:unknown,s:CurrentSession){const v=comparisonSchema.parse(raw),cur=await prisma.comparison.findFirst({where:{id,deletedAt:null}});if(!cur)return null;const slug=await uniqueSlug(v.slug||v.title,x=>exists(x,id),cur.slug);const row=await prisma.$transaction(async tx=>{await Promise.all([tx.comparisonItem.deleteMany({where:{comparisonId:id}}),tx.comparisonFeature.deleteMany({where:{comparisonId:id}})]);const c=await tx.comparison.update({where:{id},data:{title:v.title,slug,introduction:v.introduction||null,status:v.status,publishedAt:v.status==="PUBLISHED"?(v.publishedAt?new Date(v.publishedAt):cur.publishedAt||new Date()):v.publishedAt?new Date(v.publishedAt):null}});await tx.comparisonItem.createMany({data:v.items.map((x,sortOrder)=>({comparisonId:id,label:x.label,productName:x.productName,productUrl:x.productUrl||null,affiliateUrl:x.affiliateUrl||null,sortOrder}))});await tx.comparisonFeature.createMany({data:v.features.map((x,sortOrder)=>featureData(x,sortOrder,id))});return c});await auditService.record({userId:s.user.id,action:"comparison.update",entityType:"Comparison",entityId:id});return row},
  async remove(id:string,s:CurrentSession){const c=await prisma.comparison.update({where:{id},data:{status:"ARCHIVED"}});await auditService.record({userId:s.user.id,action:"comparison.archive",entityType:"Comparison",entityId:id});return c},
  publicList:()=>prisma.comparison.findMany({where:{status:"PUBLISHED",deletedAt:null,publishedAt:{lte:new Date()}},include:{items:{orderBy:{sortOrder:"asc"}},features:{orderBy:{sortOrder:"asc"},take:5}},orderBy:{publishedAt:"desc"}}),
  publicGet:(slug:string)=>prisma.comparison.findFirst({where:{slug,status:"PUBLISHED",deletedAt:null,publishedAt:{lte:new Date()}},include:{items:{orderBy:{sortOrder:"asc"}},features:{orderBy:{sortOrder:"asc"}}}})
};
